export const Voca = {
    "(기계, 방법 등이) 효율적인, 능률적인": "efficient",
    "대행 회사, 대리점": "agency",
    "~을 동봉하다; ~을 둘러싸다, 애워싸다": "enclose",
    "조심스러운, 주의 깊은": "careful",
    "수용력, 용량; 능력": "capacity",
    "이용하다, 활용하다": "utilize",
    "제조(업)의": "manufacturing",
    "(낡은 건물, 가구 등을) 개조하다, 수리하다": "renovate",
    "결정, 결단": "decision",
    "재료, 물질": "material",
    "성공, 성과": "success",
    "~의 결과로 보다": "attribute",
    "효율, 능률": "efficiency",
    "한계, 제한": "limit",
    "맞춘, 주문에 따라 맞춘": "tailored",
    "구성 요소, 부품": "component",
    "~을 할 수 있는, ~할 능력이 있는": "capable",
    "절약하다, 아끼다": "economize",
    "유연한, 융통성 있는": "flexible",
    "비교할 만한, 필적하는": "comparable",
    "생산하다": "produce",
    "각각, 제각기": "respectively",
    "장치": "device",
    "(불필요한 것을) 제거하다, 다듬다": "trim",
    "(신제품을) 출시하다": "launch",
    "따로따로, 개별적으로": "separately",
    "(기간, 임기 등의) 만료, 만기": "expiration",
    "(능숙하게) 이동시키다, 조종하다": "maneuver",
    "다가오는": "coming",
    "손상된, 피해를 입은": "damaged",
    "~을 막다, 예방하다": "prevent",
    "힘, 권력": "power",
    "화학의": "chemical",
    "불평": "complaint",
    "처리하다; 거래하다; 다루다": "deal",
    "논쟁적인, 논쟁을 좋아하는": "argumentative",
    "적절하게": "appropriately",
    "반응하다": "respond",
    "격분시키다, 몹시 화나게 하다": "infuriate",
    "정중한": "curteous",
    "만족": "satisfaction",
    "불편, ~에게 불편을 느끼게 하다": "inconvenience",
    "완성하다, 완료하다": "complete",
    "감사": "appreciation",
    "평가하다": "evaluate",
    "제안하다, 암시하다": "suggest",
    "선호": "preference",
    "경영진, 경영": "management",
    "예측하다": "predict",
    "보내다; 전달하다": "transfer",
    "상": "award",
    "의무적인": "mandatory",
    "유능한, 능숙한": "competent",
    "성능, 성과; 공연, 연주, 연기": "performance",
    "~에게 보답하다, 보상하다, 포상, 보상": "reward",
    "찾기, 수색, 조사": "search",
    "경험이 없는, 미숙한": "inexperienced",
    "시간상 이른, 조기의": "early",
    "지정하다, 지명하다": "designate",
    "경영의, 관리의": "executive",
    "헌신": "dedication",
    "만장일치로": "unanimously",
    "진전, 진행, 진보, 진행하다, 발전하다": "progress",
    "축하하다": "congratulate",
    "해고하다, 해고하다": "dismiss",
    "독립성": "independence",
    "참여, 참가, 가입": "participation",
    "칭찬": "praise",
    "성과, 업적": "accomplishment",
    "토의, 심의, 숙고": "deliberation",
    "리더십, 지도력": "leadership",
    "은퇴하다, 은퇴하다": "retire",
    "지명, 임명": "nomination",
    "재편성하다, 재조직하다": "reorganize",
    "섬기다, 일하다": "serve",
    "격려": "encouragement",
    "사임, 사직, 사직서": "resignation",
    "엄격히": "strictly",
    "(교통의) 체증, 혼잡": "congestion",
    "완화하다": "alleviate",
    "우회시키다, 다른 곳으로 돌리다": "divert",
    "우회": "detour",
    "연료": "fuel",
    "오작동, 기능불량": "malfunction",
    "허락하다, 허가증": "permit",
    "교통(수단), 운송 수단": "transportation",
    "기회": "opportunity",
    "명확하게": "clearly",
    "계속 진행 중인": "ongoing",
    "상세한": "detailed",
    "대안, 대체, 다른, 대안의": "alternative",
    "얻다, 획득하다": "obtain",
    "지정된": "designated",
    "교차로, 교차지점": "intersection",
    "갖추다, 설비하다": "equip",
    "통근하다": "commute",
    "시내에서, 도심지로": "downtown",
    "자동차의": "automotive",
    "폐쇄": "closure",
    "차량, 운송 수단": "vehicle",
    "승강장": "platform",
    "공무원, 관리, 공식적인": "official",
    "교통, 운송, 통과하다": "transit",
    "교통요금": "fare",
    "지원자, 신청자": "applicant",
    "관련시키다": "associate",
    "후보자, 지원자": "candidate",
    "증명서": "certification",
    "확신, 자신감": "confidence",
    "학위": "degree",
    "자격이 있는": "eligible",
    "고용": "employment",
    "~에게 자격을 주다": "entitle",
    "만족시키다": "meet",
    "직업": "occupation",
    "급료, 지불": "paycheck",
    "급료명부": "payroll",
    "직업의": "professional",
    "능숙, 숙달": "proficiency",
    "추천서, 침고": "reference",
    "모집하다": "recruit",
    "자격 있는": "qualified",
    "이력서": "resume",
    "필요조건": "requirement",
    "폐지하다": "abolish",
    "접근": "access",
    "~에 따라": "according to",
    "비난하다": "accuse",
    "승인, 인가": "approval",
    "변호사": "attorney",
    "~을 인가하다": "authorize",
    "~따르다": "comply with",
    "연회, 만찬":"banquet",
"기념일":"anniversary",
"필수의, 의무적인":"required",
"성공하다, 뒤를 잇다":"succeed",
"쉬다,휴식, 나머지":"rest",
"모금":"fund-raising",
"재개하다, 다시 시작하다":"resume",
"(출판물의)제 ~호; 문제, 쟁점":"issue",
"(정기발행물의) 구독":"subscription",
"나타나다, 출현하다":"appear",
"동행하다, 동반하다":"accompany",
"(간행물의)판":"edition",
"명확하게, 분명히; 특히, 특별히":"specifically",
"익명의, 이름을 모르는":"anonymous",
"헌신하다, 전념하다":"commit",
"유익한, 정보를 주는":"information",
"청중, 관중":"audience",
"작가, 저자":"author",
"주목하다; 특별히 언급하다.":"note",
"골동품":"antique",
"원고":"manuscript",
"유익한, 이로운":"beneficial",
"곧 있을, 다가오는":"upcoming",
"빌려주다":"lend",
"현재의,; 현행의, 통용되는":"current",
"지방의, 고장의":"local",
"다양성, 변화":"variety",
"옹호자":"advocate",
"기고가, 공헌자":"contributor",
"저항하다; (설명,묘사등이)거의 불가능하다":"defy",
"매혹적인, 황홀한":"fascinating",
"(영화, 연극의)상영; 전시":"showing",
"설문조사":"survey",
"분석":"analysis",
"응답자":"respondent",
"경쟁":"competition",
"항상, 일관되게":"consistently",
"수요, 요구하다":"demand",
"전력을 다하다":"do one's utmost",
"확장하다, 확대하다":"expand",
"고급의; 진보한, 앞선":"advanced",
"연기하다, 뒤로 미루다":"postpone",
"추가의, 부가적인":"additional",
"고맙게 생각하다; 높이 평가하다; 감상하다":"appreciate",
"설명; 드러냄, 시연":"demonstration",
"사다, 구입하다":"buy",
"조사하다":"examine",
"효과적인; (법률 등이)발표되는, 시행되는":"effective",
"좋아하다":"like",
"특히":"especially",
"면밀히, 엄밀히":"closely",
"예약하다, 지정하다; 보존하다":"reserve",
"협력하다, 협동하다":"cooperate",
"매우, 대단히, 아주":"very",
"연속적인":"consecutive",
"예상, 기대":"expectation",
"공표하다; 광고하다, 선전하다":"publicize",
"높이다, 올리다; (의문을)제기하다":"raise",
"극도로, 대단히":"extremely",
"~에 영향을 미치다, 불리하게 작용하다":"affect",
"목표, 목표로 삼다":"target",
"운동, 캠페인":"campaign",
"개연성이 높은, 유망한":"probable",
"집중시키다, 집중하다":"focus",
"계절의, 계절적인":"seasonal",
"영향, 충격":"impact",
"비교":"comparison",
"격차":"gap",
"증가하는, 오르는":"mounting",
"반영하는":"reflective",
"광고":"advertisement",
"약간의; 주변의":"marginal",
"고객":"customer",
"~에 영향을 주다, 영향":"influence",
"즉각적으로, 즉시":"instantly",
"창조적인, 독창적인":"creative",
"적극적으로":"aggressively",
"~을 겨누다, 목표, 목적":"aim",
"전략":"strategy",
"보여주다, 나타내다":"indicate",
"끌다, 유인하다":"attract",
"경험, 체험, 체험하다, 경험하다":"experience",
"분석하다, 분석적으로 검토하다":"analyze",
"(신제품을)발표하다, 소개하다":"introduce",
"조언해주다, 충고하다":"advise",
"구독하다":"subscribe",
"부재; 결근, 결석":"absence",
"방법, 수단":"means",
"(다른 것보다)~을 더 좋아하다, 선호하다":"prefer",
"이점, 강점":"advantage",
"앞으로, (물건, 정보를)보내다":"forward",
"동시대의; 현대의, 당대의":"contemporary",
"토론, 토의":"discussion",
"처음의, 최초의":"initial",
"착실하게; 꾸준히":"steadily",
"반드시":"necessarily",
"(문제 등을)해결하다":"resolve",
"간파하다, 탐지하다":"detect",
"강화하다, 증대하다, 강렬하게 만들다.":"intensify",
"호의적으로; 순조롭게":"favorably",
"포함하다; 지불하다; 덮다":"cover",
"보다 적은, 덜한":"less",
"대부분, 대다수":"majority",
"채택하다":"adopt",
"주로, 대부분":"largely",
"소홀히 하다, 무시하다":"disregard",
"노력":"effort",
"혜택, 장려금":"incentive",
"필요, 요구, 욕구, ~할 필요가 있다.":"need",
"(계획 등의)입안자, 지도자":"mastermind",
"침체된, 불경기의, ":"stagnant",
"극적으로":"dramatically",
"활발한, 호황의":"brisk",
"불안정한, 변하기 쉬운":"unstable",
"급속히, 빨리":"rapidly",
"(물가 등이)폭등하다, 높이 치솟다":"soar",
"단언하다, 주장하다 ":"assert",
"(경기를)부양시키다, 상승시키다":"boost",
"분석가":"analyst",
"잠재적인":"potential",
"만족해하는, 기쁜":"pleased",
"계속~한 상태이다; 아직 ~해야한다":"remain",
"제한된, 한정된":"limited",
"비용이 많이 드는, 손실이 큰":"costly",
"특정한, 독특한, 세심한 ":"particular",
"과감한, 급격한":"drastic",
"고르게, 균등하게":"evenly",
"증거":"evidence",
"전망, 예상 ":"prospect",
"이글다, 지휘하다; (어떤 결과에)이르다":"lead",
"(값, 가치가)하락하다":"fall",
"기간, 시기":"period",
"지표, 지수":"indicator",
"산업":"industry",
"~할 것 같은":"likely",
"붐, 호황":"boom",
"임원, 책임자":"director",
"대용품, 대신하다":"substitute",
"결과":"consequence",
"상당히, 꽤":"fairly",
"경제적인, 절약되는":"economical",
"번영하다, 성공하다":"thrive",
"영향, 밀접한 관계":"implication",
"감소, 감퇴":"wane",
"번영 ":"prosperity",
"불황 ":"depression",
"줄어들다, 감소되다":"dwindle",
"저해하다, 방해하다":"impede",
"유망한, 전망이 좋은":"promising",
"역경, 불운":"adversity",
"구매하다, 구매":"purchase",
"할부":"installment",
"(가격이)알맞은, 감당할 수 있는":"affordable",
"정확히":"exactly",
"경매":"auction",
"진정한, 진짜의, 진품의":"authentic",
"요금,청구,금액;책임,의무~을 청구하다; (외상으로)달아놓다":"charge",
"통지, 공고":"notice",
"경험이 있는, 노련한, 능숙한":"experienced",
"설명, 지시 ":"instruction",
"전문가, 전문가의, 전문적인":"expert",
"(품질 등의)보증, 보증서":"warranty",
"환불, 환불금":"refund",
"가입자, 구독자":"subscriber",
"배달":"delivery",
"가격":"price",
"영수증":"receipt",
"제공하다, 제공,오퍼":"offer",
"주의깊게, 신중히":"carefully",
"혜택, 이익, 혜택을 보다, 이익을 얻다":"benefit",
"오로지, 독점적으로":"exclusively",
"(제품등의)설명, 해설":"description",
"상대적으로":"relatively",
"아끼다, 할애하다, 예비의, 여분의":"spare",
"준비, 대비":"preparation",
"지역, 구역":"area",
"정리, 없애기; 허가":"clearance",
"(성질, 형상을)고치다, 바꾸다":"alter",
"적용하다; 지원하다":"apply",
"서로, 상호 간에 ":"mutually",
"방식, 방법":"method",
"용인되는, 받아들일 수 있는;훌륭한, 만족스러운":"acceptable",
"욕구, 갈망, 원하다, 바라다":"desire",
"(현금,상품과)교환할 수 있는, 환급할 수 있는":"redeemable",
"공식적으로":"officially",
"소비(량), 소모 ":"consumption",
"~의 자격을 얻다":"qualify",
"섬유, 천":"fabric",
"유효한":"valid",
"노점상, 가판대; 판매업체":"vendor",
"연구, 조사":"research",
"고안하다, 발명하다":"devise",
"혁명적인":"revolutionary",
"혁신적인":"innovative",
"특징, 특색, 특징으로 삼다, 특별히 포함하다":"feature",
"영감":"inspiration",
"충분히":"sufficiently",
"특허, 특허권, 특허품":"patent",
"(장래의 일 등을)계획하다, 상상하다":"envision",
"연장하다; (기간을)늘리다;(감사의 뜻을)말하다, 베풀다":"extend",
"~후에, 다음의, 다음에 오는":"following",
"~할 작정이다; 의도하다":"intend",
"(인정하여 정식으로)수여하다, 주다,(연구비, 장학금등의)보조금":"grant",
"~하게 하다, ~을 허락하다":"allow",
"~을 검사하다, 조사하다":"inspect",
"향상시키다, 개선하다":"improve",
"점점, 더욱 더":"increasingly",
"투자하다, 운용하다":"invest",
"여러 가지의, 가지각색의":"various",
"업그레이드, 개량형업그레이드하다, 개선하다":"upgrade",
"설명서, 안내서":"manual",
"조사하다, 탐구하다":"explore",
"응답, 대답":"response",
"외관, 외모":"appearance",
"성공적인, 성공한":"successful",
"~을 수용하다, ~을 담다;(회의 등을)개최하다, 열다":"hold",
"진보, 전진":"advance",
"믿을 만한, 신뢰할 수 있는":"reliable",
"품질, 질":"quality",
"국내의, 국산의":"domestic",
"개발, 발전":"development",
"(입수)가능성, 유효성, 유용성":"availability",
"갱신, 개정, 갱신하다,최신의 것으로 하다":"update",
"정확한":"accurate",
"복잡한":"complicate",
"숙련된, 노련한":"accomplished",
"문의, 질문":"inquiry",
"징후, 조짐":"indication",
"제조회사, 제조업자":"manufacturer",
"호환되는, 양립할 수 있는":"compatible",
"우수한, 상급의":"superior",
"완전한, 완전무결한":"absolute",
"넓히다":"broaden",
"부식":"corrosion",
"장비, 설비":"epuipment",
"자동화하다":"automate",
"명세서, 설명서, 사양":"specification",
"제대로, 정확하게":"properly",
"안전":"safety",
"예방조치, 예방책":"precaution",
"(기계 등이)작동하다, 움직이다":"operate",
"가공, 처리":"processing",
"용량, 수용력; 역할":"capacity",
"(부품,기계 등을)조립하다;(사람을)모으다":"assemble",
"이용하다, 활용하다":"utilize",
"~을-한 상태에 두다;(지시,주문,신청등을)하다":"place",
"~을 채우다; (주문대로)이행하다":"fill",
"제조(업)의":"manufacturing",
"(낡은 건물, 가구등을)개조하다,수리하다, 보수하다":"renovate",
"결정, 판단":"decision",
"재료, 물질":"material",
"성과, 성공":"success",
"(원인을)~의 덕분으로 돌리다":"attribute",
"효율, 능률":"efficiency",
"한계, 제한":"limit",
"맞춤의, 주문에 따라 맞춘":"tailored",
"부품, (구성)요소":"component",
"~을 할 수 있는, ~할 능력이 있는":"capable",
"절약하다, 아끼다":"economize",
"융통성 있는; 유연한, 잘 구부러지는":"flexible",
"필적하는, 비교되는":"comparable",
"생산하다":"produce",
"각각, 따로":"respectively",
"장치":"device",
"(깍아)다듬다, 없애다; 삭감하다":"trim",
"(신제품을)출시하다":"launch",
"개별적으로, 따로따로":"separately",
"(기간,임기 등의)만료, 만기":"expiration",
"이동시키다, 움직이다":"maneuver",
"다가오는":"coming",
"손상된, 손해를 입은":"damaged",
"~을 막다, ~을 예방하다":"prevent",
"전력, 전기":"power",
"화학제품":"chemical",
"불평":"complaint",
"처리하다; 거래하다; 분배하다":"deal",
"논쟁적인, 논쟁을 좋아하는":"argumentative",
"적절하게":"appropriately",
"응답하다":"respond",
"화나게하다, 격분시키다":"infuriate",
"예의바른":"curteous",
"만족":"satisfaction",
"불편, ~에게 불편을 느끼게 하다":"inconvenience",
"완료하다, 완성하다, 완료된, 완성된":"complete",
"구체적인, 명확한":"specific",
"반환하다, 반송하다":"return",
"~을 교체하다, 대체하다":"replace",
"발표":"presentation",
"평가":"evaluation",
"자신 있는":"confident",
"~을 야기하다, ~의 원인이 되다원인":"cause",
"해설, 설명":"commentary",
"통지":"notification",
"사과하다":"apologize",
"소통하다, 교류하다; 상호작용을 하다":"interact",
"확신하는, 확실한; 특정한":"certain",
"헌신, 전념":"commitment",
"~에게 박수를 보내다; 칭찬하다":"applaud",
"약력, 전기":"biography",
"비판적인; 중요한; 위기의":"critical",
"~에 달려 있다, ~에게 의존하다":"depend on",
"결합시키다":"combine",
"우선권, 우선사항":"priority",
"관찰하다, 주시하다;(규칙 등을)준수하다, 지키다":"observe",
"결함이 있는":"defective",
"반영하다, 나타내다":"reflect",
"태도, 마음가짐":"attitude",
"실망시키다":"disappoint",
"문의하다, 질문하다":"inquire",
"삽입하다":"insert",
"공개하다, 드러내다":"disclose",
"보장하다, 보장":"guarantee",
"공손하게, 예의바르게":"politely",
"진지하게":"seriously",
"국제적인":"international",
"관광 명소":"attraction",
"여행 일정":"itinerary",
"이국적인, 매혹적인":"exotic",
"다양한":"diverse",
"최고의, 뛰어난":"superb",
"수화물":"baggage",
"목적지":"destination",
"분실된, 없어진":"missing",
"(~의 위치를)찾아내다;~을 위치시키다":"locate",
"대략":"approximately",
"관세,세금; 직무,의무":"duty",
"과정, 처리하다":"process",
"탑승하다, 이사회":"board",
"편안한":"comfortable",
"(세관에서)신고하다":"declare",
"명시하다 ":"specify",
"출발하다":"depart",
"비상시, 비상 사태":"emergency",
"승객":"passenger",
"(장소를)출발하는, 떠나는;(지위를)떠나는":"outgoing",
"단단히, 꽉":"tighly",
"(공장,시설 등의)견학, 짧은 여행":"tour",
"항공사, 수송기, 수송 회사":"carrier",
"관례상, 습관적으로":"customarily",
"혼란시키다 ":"confuse",
"도착하다":"arrive",
"(홍보용)소책자, 브로셔":"brochure",
"수반하다, 포함하다; 참여시키다":"involve",
"(배나 다른 운송 수단으로)운송하다, 수송하다, 선박, 배":"ship",
"여행가방":"suitcase",
"이용할 수 없는, 구할 수 없는":"unavailable",
"(서류에)기입하다, 적어 넣다":"fill out/in",
"세관":"customs",
"떨어져서":"away",
"멋진, 극적인; 급격한":"dramatic",
"환대, 친절":"hospitality",
"빠지다, 탐닉하다":"indulge",
"가까움, 근접함":"proximity",
"(집합적)좌석 설비; 좌석 배열":"seating",
"무제한의":"unlimited",
"제안, 계획":"proposal",
"동맹, 제휴":"alliance",
"계약 조건":"stipulation",
"조건; 임기, 기한":"term",
"타협, 화해":"compromise",
"협상, 교섭":"negotiation",
"계약, 협정; 합의":"agreement",
"교착 상태":"deadlock",
"검토하다, 재조사하다":"review",
"계약(서),계약하다, 수축하다":"contract",
"서명":"signature",
"원래, 처음에는":"originally",
"방향, 지시, 감독":"direction",
"처음에, 초기에":"initially",
"(계약등이)만료되다":"expire",
"협력하다, 공동으로 일하다":"collaborate",
"전념하다, 헌신하다, 바치다":"dedicate",
"수정된, 변경된":"revised",
"반드시 해야 하는, 필수적인":"imperative",
"협력하여, 협조적으로":"cooperatively",
"수수료, 커미션; 위원회(일 등을)의뢰하다, 주문하다":"commission",
"빠뜨리다, 생략하다":"omit",
"대립, 충돌, 갈등":"conflict",
"(계약 등을)갱신하다":"renew",
"능숙한, 능한":"proficient",
"기밀, 비밀":"confidentiality",
"분쟁, 논쟁":"dispute",
"반대, 이익":"objection",
"규정하다, 정의하다":"define",
"인상":"impression",
"보안, 안전, 보호":"security",
"선택권":"option",
"(일을)진행하다, 진척되다":"proceed",
"수정하다, 일부 변경하다":"modify",
"(범위 등을)좁히다":"narrow",
"입찰":"bid",
"해결하다, 처리하다":"settle",
"끝내다, 종결시키다":"terminate",
"도전적인, 힘든":"challenging",
"토대, 기초":"foundation",
"전적으로, 완전히":"completely",
"거절하다":"refuse",
"일시적으로":"temporarily",
"판매업자, 상인":"dealer",
"대량의":"bulk",
"재고품, 재고목록":"inventory",
"부족한":"short",
"비용":"cost",
"선택된 것, 정선품":"selection",
"상업의, 상업적인, 광고":"commercial",
"주문하다, 주문, 주문품":"order",
"공급하다, 제공하다":"provide",
"~와 연락하다,(상업적 목적으로)교섭하고 있는 사람":"contact",
"송장":"invoice",
"옮기다, 움직이다, 조치, 수단;이동, 이사":"move",
"공급하다, 공급; (-s)비품, 소모품":"supply",
"할인":"discount",
"배포하다, 배급하다":"distribute",
"인수; 구입한 것":"acquisition",
"~에게 보장하다, ~을 안심시키다, 장담하다":"assure",
"~의 영향을 받기 쉬운;(동의 등을)조건으로 하는,~에게(~을) 받게 하다":"subject",
"구하다, 찾다":"seek",
"만족스러운":"satisfactory",
"확인, 확증":"confirmation",
"~할 수 없는":"unable",
"지불(금액),납입(금액)":"payment",
"대책, 조치, 수단측정하다":"measure",
"특가품, 흥정":"bargain",
"재고; 주식":"stock",
"감당할 수 있는 비용":"affordability",
"(집합적)고객들,(변호사,건축가 등의)모든 의뢰인":"clientele",
"호평, 찬사":"acclaim",
"~을 대표하다":"represent",
"등급, 평가":"rating",
"포함하다, 둘러싸다":"encompass",
"마무리 짓다, 완결하다":"finalize",
"시장":"market",
"소매":"retail",
"상품, 산물":"commodity",
"견적(액), 견적을 내다":"quote",
"위탁 판매":"consignment",
"깨지기 쉬운":"fragile",
"부패하기 쉬운":"perishable",
"배달하다; (연설을)하다":"deliver",
"확실하게 하다, 보장하다":"ensure",
"급송 택배, 운반인":"courier",
"(큰)판지상자":"carton",
"주소,(어려운 문제 등을)처리하다,다루다":"address",
"선적, (화물의)발송;수송품, 적하물":"shipment",
"특히":"particularly",
"적절히":"adequately",
"물품, 물건; 기사, 논설":"article",
"(기계, 방법 등이)효과적인,능률적인":"efficient",
"대행 회사, 대리점":"agency",
"~을 동봉하다; ~을 둘러싸다, 애워싸다":"enclose",
"조심스러운, 주의 깊은":"careful",
"~을 찾다; (사람,물건 등을) 도중에 태우다":"pick up",
"지니다; (물건을)팔다, 가게에 놓다":"carry",
"붙이다, 접착하다, 첨부하다":"attach",
"이전에":"formerly",
"소포, 꾸러미":"package",
"반응하다, 대응하다":"react",
"내용물":"content",
"편의, 편리":"convenience",
"인정하다; (편지 등의)수령을 알리다, 감사하다":"acknowledge",
"주의, 조심":"caution",
"편지, 통신문":"correspondence",
"분리하다; 분류하다":"separate",
"현저한, 두드러진":"remarkable",
"취급하다, 다루다":"handle",
"창고, 저장소":"warehouse",
"(세금 등을)부과하다":"impose",
"보관소, 저장소":"storage",
"분리하다, 떼다":"detach",
"봉투":"envelope",
"제외, 배제":"exclusion",
"수신자":"recipient",
"(우표 등을)붙이다":"affix",
"부정확한":"incorrect",
"어쩔 수 없이 ~하게 하다,~에게 강요하다":"oblige",
"단계; 조치, 수단":"step",
"체크인하다, 숙박 수속을 하다":"check in",
"보상하다":"compensate",
"무료의, 우대의":"complimentary",
"주방장":"chef",
"용기, 그릇":"container",
"우아한, 고상한":"elegant",
"맛, 풍미":"flavor",
"(건물 등이)~을 수용하다, 숙박시키다;(충분한 공간을) 제공하다(조건, 요구 등을)만족시키다":"accommodate",
"(사물이)이용 가능한;(사람이) 시간이 있는":"available",
"환영회; (호텔, 회사, 병원 등의)접수처":"reception",
"미리, 사전에":"in advance",
"다과, 가벼운 음식물":"refreshments",
"~을 하다, ~을 만들다":"make",
"(연회 등의)음식물을 공급하다":"cater",
"예약, 지정; 보호구역":"reservation",
"음료":"beverage",
"확인하다":"confirm",
"취소하다":"cancel",
"요금":"rate",
"편리하게":"conviniently",
"장식하다":"decorate",
"정보, 자료":"information",
"유지하다, 보유하다":"retain",
"분위기, 환경":"atmosphere",
"(독특한)요리":"cuisine",
"순서, 차례":"sequence",
"광범위한, 넓은":"extensive",
"전의, 먼저의":"prior",
"예약하다":"book",
"편의 시설":"amenity",
"소지품, 소유물":"belongings",
"완전히":"entirely",
"완화시키다, 쉬움, 용이함":"ease",
"재료, 성분":"ingredient",
"음미하며 마시다, 홀짝거리다":"sip",
"휘젓다, 뒤섞다":"stir",
"선택물, 선택 사항, 선택":"choice",
"복잡한 문제":"complication",
"신선함":"freshness",
"(호텔등의)이용률":"occupancy",
"감소, 하락,(초대,신청을)거절하다":"decline",
"현저하게, 눈에 띄게":"markedly",
"인상, 증가, 증가하다":"increase",
"수입":"revenue",
"예상(치)":"projection",
"상당한":"substantial",
"예상하다, 기대하다":"anticipate",
"상당히, 두드러지게":"significantly",
"추정하다, 추산하다, 추정(치), 추산":"estimate",
"옮기다, 이동하다, 변화, 교대근무":"shift",
"요금, 수수료":"fee",
"생산량, 생산":"production",
"(-s)매출액, 매상고; (할인)판매":"sale",
"굉장한, 인상적인":"impressive",
"직원, 외판원; 대표자":"representative",
"최근의":"recent",
"~을 초과하다":"exceed",
"향상":"improvement",
"고용주":"employer",
"정기적인; 단골의":"regular",
"요약하다":"summarize",
"보통, 일반적으로":"typically",
"전체의, 온전한":"whole",
"성장, 발전":"growth",
"총액, 합계 수":"figure",
"꾸준한; 안정된":"steady",
"빈번한, 잦은":"frequent",
"달성하다, 성취하다":"achieve",
"추정, 산정, 가정":"assumption",
"공유하다, 함께쓰다;(생각, 경험, 감정을 남과)함께 나누다몫, 지분":"share",
"(손실을)입다, (빚을)지다":"incur",
"약간":"slightly",
"수익, 이익":"profit",
"의존하는, 의지하는":"reliant",
"분명히 보여주다, 설명하다":"illustrate",
"부정확한":"inaccurate",
"비율, 백분율":"percentage",
"줄이다, 감소시키다":"reduce",
"~하는 경향이 있다, ~하기 쉽다":"tend",
"회계 감사, 심사":"audit",
"회계":"accounting",
"예산":"budget",
"재정의, 금전상의":"financial",
"~을 줄이다, 삭감하다":"curtail",
"적자, 부족액":"deficit",
"최근에":"recently",
"크게, 상당히":"substantially",
"위원회":"committee",
"자주, 흔히":"frequently",
"능력, 역량":"capability",
"수익금":"proceeds",
"변제하다, 상환하다":"reimburse",
"상당히, 많이":"considerably",
"충분한, 적절한":"adequate",
"총계의, 전부의":"total",
"할당하다, 배분하다":"allocate",
"조사관, 감독관":"inspector",
"선호되는, 우선의":"preferred",
"사분기; 4분의1":"quarter",
"중단시키다, 방해하다":"interrupt",
"흝어보다, 둘러보다":"browse",
"즉각적인; 신속한, 촉발하다, 유도하다":"prompt",
"공제하다, 빼다":"deduct",
"측정, 측량; 치수":"measurement",
"단축하다, 짧게하다":"shorten",
"수정하다":"amend",
"계산하다, 산출하다":"calculate",
"면제된, ~이 없는":"exempt",
"부족한, 불충분한":"deficient",
"비교하다":"compare",
"운 좋은":"fortunate",
"지출, 비용":"expenditure",
"정확하게":"accurately",
"~의 가치가 있는, (얼마)어치, 가치":"worth",
"초과, 초과량":"excess",
"회계의, 재정상의":"fiscal",
"부수적인":"incidental",
"물가상승, 인플레이션, 통화팽창":"inflation",
"책임져야 할; ~하기 쉬운":"liable",
"~을 쓰다, 소비하다":"spend",
"총 매상고, 거래액; 이직률":"turnover",
"발표하다":"announce",
"관련 있는; 관심이 있는":"interested",
"적극적인, 활발한":"active",
"수락하다, 승낙하다":"accept",
"예견하다, 예감하다":"foresee",
"확장, 팽창":"expansion",
"(공장 등을)이전하다":"relocate",
"경쟁업체, 경쟁자":"competitor",
"자산":"asset",
"기여하다, 공헌하다":"contribute",
"(목표 등에)전념하는, 헌신적인":"dedicated",
"잃어버리다, 위치를 잘못 잡다":"misplace",
"(정도나 양이)상당한":"considerable",
"지속되다":"last",
"부상하다, 나타나다":"emerge",
"성장하다, 성장시키다, 증가시키다":"grow",
"선발하다, 선택하다":"select",
"합병하다, 병합하다":"merge",
"암시하다, 넌지시 나타내다, 의미하다":"imply",
"필수적인":"vital",
"(집요하게)계속하다, 계속되다, 지속되다":"persist",
"독립적인, 독자적인":"independent",
"세력":"force",
"설립하다":"establish",
"(사업 등을) 착수하다, 시작하다":"initiate",
"(질 등을) 향상시키다, 높이다, 강화하다":"enhance",
"저명한, 유명한, 명성이 있는":"renowned",
"정보에 근거한":"informed",
"회의록":"minutes",
"(권리,청구등을)포기하다":"waive",
"(치수,양 등이)~에 달하다;~에 도착하다":"reach",
"권한; 당국":"authority",
"매입하다, 취득하다":"acquire",
"~을 능가하다, 넘어서다":"surpass",
"~을 운영하다, 경영하다":"run",
"사실이라고 생각할 수 없는,일어날 것 같지 않은":"improbable",
"우위, 유리함; 가장자리, 끝":"edge",
"동시에":"simultaneously",
"밝히다, 누설하다":"reveal",
"생산성":"productivity",
"확신이 없는, 불확실한":"uncertain",
"으뜸의, 첫째의":"premier",
"의제, 의사일정":"agenda",
"(회원 등이)모이다, (회의가)개최되다":"convene",
"부인하다, 반박하다":"refute",
"조정":"coordination",
"만장일치의, 동의하는":"unanimous",
"납득시키다, 확신시키다":"convince",
"여론, 일치된 의견":"consensus",
"연기하다, 미루다":"defer",
"보통, 일반적으로":"usually",
"일정을 바꾸다":"reschedule",
"회의":"meeting",
"알아내다; 결정하다, 확정하다":"determine",
"보고하다; 출두하다,(직장,회의 등에 도착을)알리다,보고서; 보도, 기록":"report",
"논평하다, 언급하다":"comment",
"단계":"phase",
"승인하다, 찬성하다":"approve",
"동봉된":"enclosed",
"쉬운, 용이한":"easy",
"기록; 경력, 이력, 기록하다":"record",
"제안":"suggestion",
"주의, 경청":"attention",
"반대하다":"object",
"우연히, 일치하게, 동시 발생적으로":"coincidentally",
"붐비는, 복잡한":"crowded",
"겪다, 거치다, 경험하다":"undergo",
"결과":"outcome",
"주의 깊게, 좁게; 가까스로, 간신히, 겨우":"narrowly",
"의견을 달리하다, 다르다":"differ",
"논의하다, 토론하다":"discuss",
"(연설, 수업 등을)하다":"give",
"~에게 간단히 설명하다, 브리핑하다":"brief",
"(주의를)산만하게 하다, 빗기게 하다":"distract",
"강조, 중점":"emphasis",
"언론(계),보도기관, 누르다":"press",
"준비하다, 조직하다, 정리하다":"organize",
"언급하다":"mention",
"설득력 있는":"persuasive",
"이해심 있는":"understanding",
"(회의 등을)휴회하다":"adjourn",
"건설적인":"constructive",
"(회의의)사회를 보다, ~의 의장을 맡아보다":"preside",
"관계가 없는, 무관한":"irrelevant",
"제한":"constraint",
"(대회 등을)주최하다":"host",
"매년의":"annual",
"목적, 의도":"purpose",
"등록하다":"enroll",
"강의, 강연":"lecture",
"참가자":"participant",
"참석하다, 출석하다":"attend",
"장려하다, 복돋아주다":"encourage",
"휴가, 떠나다, 남기다":"leave",
"추천사항, 추천":"recommendation",
"회의, 회담":"conference",
"~을 예정하다":"schedule",
"포함하다":"include",
"결과,(~의 결과로)되다":"result",
"등록하다":"register",
"요구하다":"require",
"고마워하는, 감사하는":"grateful",
"초과근무, 야근":"overtime",
"부담, 책임, 의무":"responsibility",
"찬성하다, 승인, 동의":"assent",
"~을 -으로 간주하다, 여기다,관심,배려":"regard",
"임시적인, 잠정적인":"tentative",
"반가운, 기꺼이 받아들여지는":"welcome",
"행사, 연회":"function",
"시작되다":"commence",
"목표, 목적":"objective",
"신이 난, 들뜬":"excited",
"상환, 변제, 배상":"reimbursement",
"대우, 처우":"treatment",
"존경, 명예":"honor",
"강조하다":"emphasize",
"(경기 등의)참가자, 출품물":"entry",
"상여금, 보너스":"bonus",
"급여":"salary",
"(금전 등을)벌다; (평판을)받다, 얻다":"earn",
"(문제 등이)발생하다, 일어나다":"arise",
"노동":"labor",
"노동조합":"union",
"기존의, 현행의":"existing",
"착취하다, 부당하게 이용하다":"exploit",
"임명하다, 지명하다":"appoint",
"평가":"appraisal",
"승진시키다; 촉진하다":"promote",
"숙련된, 노련한":"skilled",
"완전히, 철저히, 근본적으로":"radically",
"뛰어난, 예외적인":"exceptional",
"감사":"appreciation",
"평가하다":"evaluate",
"제안하다, 추천하다":"suggest",
"선호":"preference",
"경영진, 경영":"management",
"예측하다":"predict",
"보내다; 전근시키다":"transfer",
"상":"award",
"의무적인":"mandatory",
"유능한, 능숙한":"competent",
"실적,성과; 공연,연주, 연기":"performance",
"~에 보답하다, 보상하다, 포상,보상":"reward",
"찾기, 수색, 조사":"search",
"경험없는, 미숙한":"inexperienced",
"시간상 이른, 조기의":"early",
"지명하다, 지정하다":"designate",
"경영의,관리의":"executive",
"헌신":"dedication",
"만장일치로":"unanimously",
"진행, 진척, 진전, 진보하다, 발전하다":"progress",
"축하하다":"congratulate",
"해임하다, 해고하다":"dismiss",
"독립성":"independence",
"참여, 참가, 가입":"participation",
"칭찬":"praise",
"성과,업적":"accomplishment",
"토의, 심의, 숙고":"deliberation",
"리더십, 지도력":"leadership",
"퇴직하다, 은퇴하다":"retire",
"임명, 지명":"nomination",
"재편성하다, 재조직하다":"reorganize",
"근무하다, 일하다":"serve",
"격려":"encouragement",
"사임, 사직, 사직서":"resignation",
"엄격히":"strictly",
"(교통의)체증, 혼잡":"congestion",
"완화하다":"alleviate",
"우회시키다, 다른 곳으로 돌리다":"divert",
"우회":"detour",
"연료":"fuel",
"오작동, 기능불량":"malfunction",
"허락하다, 허가증":"permit",
"교통(수단), 운송 수단":"transportation",
"기회":"opportunity",
"명확히":"clearly",
"계속 진행 중인":"ongoing",
"상세한":"detailed",
"대안, 대체, 다른, 대신의":"alternative",
"획득하다, 얻다":"obtain",
"지정된":"designated",
"교차로, 교차지점":"intersection",
"갖추다, 설비하다":"equip",
"통근하다":"commute",
"시내에서, 도심지로":"downtown",
"자동차의":"automotive",
"폐쇄":"closure",
"차량, 운송 수단":"vehicle",
"승강장":"platform",
"공무원, 관리, 공식적인":"official",
"교통, 수송, 통과하다":"transit",
"교통요금":"fare",
"비용, 지출":"expense",
"신뢰, 신임, 믿다, 신뢰하다":"trust",
"(~의 방향으로)나아가다, 향하게 하다":"head",
"(차 등을)운전하다, 타고가다, 조종하다":"drive",
"벌금":"fine",
"지나가다, 통과하다":"pass",
"(매듭 등이)단단하게, 튼튼하게":"securely",
"눈에 잘 띄게, 두드러지게":"prominently",
"예약된, 예약한; 지정된":"reserved",
"평균치, 평균":"average",
"충돌":"collision",
"견인하다":"tow",
"뒤의, 반대의":"reverse",
"(전망 등을)가리다, 차단하다;(도로 등을)막다":"obstruct",
"(세금 등이)연체된, 미불의":"delinquent",
"(지불,반납 등의)기한이 지난, 지불 기한이 넘은":"overdue",
"유감스럽게도":"regrettably",
"잔고, 차감 잔액":"balance",
"입금하다, 예금하다":"deposit",
"조사 ":"investigation",
"계좌; 설명; 고려":"account",
"명세서, 성명서":"statement",
"액수, 양":"amount",
"(예금의)인출":"withdrawal",
"이전에":"previously",
"만기가 된, 지불 기일이 된;(금전 등이)~에게 마땅히 지급되어야 할":"due",
"받다, 수취하다":"receive",
"예상하다, 기대하다":"expect",
"증명서, 증서":"certificate",
"서류, 문서":"document",
"소비; 지출":"spending",
"성공적으로":"successfully",
"~에게 청구서를 보내다, 청구서, 계산서":"bill",
"즐거움, 기쁜, 영광":"pleasure",
"연구":"study",
"요약, 개요":"summary",
"임시의":"temporary",
"(양,가격을)줄이다":"lower",
"거래, 업무":"transaction",
"두배로 만들다":"double",
"신분증, 신분 증명서":"identification",
"불만, 불평":"dissatisfaction",
"공통으로, 공동으로":"in common",
"관심; 권리; 이자":"interest",
"거절하다, 거부하다":"reject",
"관계":"relation",
"임시로, 시험적으로":"tentatively",
"그렇지 않으면, 그 대신에":"alternatively",
"주의 깊은, 세심한":"attentive",
"전환하다, 변환하다":"convert",
"몹시, 심하게":"heavily",
"대출, 대출금":"loan",
"예기치 않은":"unexpected",
"현금으로 바꾸다":"cash",
"(담보)대출":"mortgage",
"지불해야 하는":"payable",
"개인의":"personal",
"투자, 투자금":"investment",
"수익성 있는, 돈벌이가 되는":"incrative",
"본질적으로":"inherently",
"확보하다, 얻어 내다;안전하게 지키다, 고정시키다":"secure",
"예견할 수 있는":"foreseeable",
"타고난":"innate",
"재산":"property",
"~을 대신해서":"on behalf of",
"임대차(계약)":"lease",
"후원하다, 후원자":"sponsor",
"제안하다":"propose",
"후원, 원조, 지지, 지원하다,후원하다; 살게하다,(생명, 기력 등을)유지하다":"support",
"분배, 배급":"distributuion",
"고려하다":"consider",
"거의, 대략":"nearly",
"동의, 허락, 동의하다":"consent",
"고마움, 감사":"gratitude",
"상의하다, 상담하다":"consult",
"조언, 충고":"advice",
"부분적으로, 일부분은":"partially",
"분명한, 명백한,":"evident",
"신뢰도, 믿음직함":"reliability",
"조심하는, 신중한":"cautious",
"식견, 통찰력":"insight",
"포트폴리오, 투자 자산 구성":"portfolio",
"가능한, 있음직한":"possible",
"추측":"speculation",
"오로지, 혼자서, 전적으로":"solely",
"사업가":"entrepreneur",
"결국, 마침내":"eventually",
"주주":"shareholder",
"전망":"outlook",
"안정, 안정성":"stability",
"채권":"bond",
"가치 하락, 화폐의 구매력 저하":"depreciation",
"증가하는":"increasing",
"유행하고 있는, 널리 퍼진":"prevalent",
"빠른, 신속한":"rapid",
"전례 없는":"unprecedented",
"(이윤을) 가져오다, 산출하다":"yield",
"가구가 비치된":"furnished",
"거주지, 주택":"residence",
"(공간이)넓은":"spacious",
"(방 등을 커튼 등으로)장식하다":"drape",
"(집 등이)비어 있는, 사람이 살지 않는":"unoccupied",
"수리, 개조":"renovation",
"적당한, 적합한":"appropriate",
"연기하다, ~을 뒤로 미루다":"delay",
"지역 사회, 공동체":"community",
"건설, 건축":"construction",
"수리하다":"repair",
"현재":"currently",
"정기적으로":"regularly",
"배열하다, 정돈하다":"arrange",
"장소, 위치":"location",
"복구하다, 회복시키다":"restore",
"현재":"presently",
"많은":"numerous",
"그만두다; 버리다":"abandon",
"계약자, 도급업자":"contractor",
"개발하다":"develop",
"유지하다, 관리하다":"maintain",
"빽빽이, 밀집하여":"densely",
"준비하다, 채비를 갖추다":"prepare",
"결국, 마침내":"finally",
"지역, 지구":"district",
"재개발":"renewal",
"의무적인":"compulsory",
"방해하다, 해치다":"interfere",
"이전, 재배치":"relocation",
"완전히, 전적으로":"totally",
"실제로, 사실은":"actually",
"건축가":"architect",
"확장하다, 확대하다":"enlarge",
"설치하다, 장치하다":"install",
"영구적인":"permanent",
"생각하다, 추측하다":"suppose",
"인접한":"adjacent",
"구성되다, 이루어지다":"consist",
"공공시설; 공공요금":"utility",
"보전하다, 유지하다":"conserve",
"가능성, 기회":"chance",
"(날씨의)예보":"forecast",
"쓰레기, 폐기물":"waste",
"처분하다, 처리하다":"dispose",
"재활용":"recycling",
"맑게 갠; 명백한, 분명한또렷하게, 완전히; 떨어져서":"clear",
"피해, 손해, 손상시키다":"damage",
"상당한; 중대한, 중요한":"significant",
"해결책":"solution",
"(일이)발생하다, 생기다":"occur",
"이상적인":"ideal",
"보존하다, 보호하다":"preserve",
"원조, 돕다":"aid",
"지나친, 과도한":"excessive",
"집중적으로":"intensively",
"다르다, 다양하다":"vary",
"즐거운, 기분 좋은, 만족스러운":"pleasing",
"점수, 평점, 표시, 축하하다":"mark",
"접근이 불가능한, 이용이 불가능한":"inaccessible",
"방해하다":"disturb",
"오염물질":"pollutant",
"배기가스, 방출":"emission",
"빽빽한, 밀집한":"dense",
"환경적인":"environmental",
"일치하는, 지속적인, 한결같은":"consistent",
"누출, 누출량":"leak",
"단체":"organization",
"계속해서":"continually",
"오염시키다":"contaminate",
"재난":"disaster",
"방출하다":"discharge",
"자원, 자료":"resource",
"유명한, 두드러진":"prominent",
"고갈시키다":"deplete",
"정화시키다":"purify",
"멸종 위기에 처한":"endangered",
"멸종":"extinction",
"가뭄":"drought",
"(고통,피해를)입히다, 가하다":"inflict",
"이동, 이주":"migration",
"생태, 자연환경":"ecology",
"(동, 식물의)서식지":"habitat",
"피로":"fatigue",
"건강 진단":"checkup",
"증상":"symtom",
"내과의사":"physician",
"진단":"diagnosis",
"(약을)처방하다, 규정하다":"prescribe",
"회복, 쾌유":"recovery",
"인정하다, 알아보다":"recognize",
"~에 가입하다":"join",
"종합적인, 포괄적인":"comprehensive",
"참여하다, 참가하다":"participate",
"권고하다, 추천하다":"recommend",
"필요한":"necessary",
"능력":"ability",
"수술":"operation",
"청결":"cleanliness",
"지속 기간, 지속":"duration",
"진찰, 검사":"examination",
"제거하다":"eliminate",
"쉽게":"easily",
"치과의":"dental",
"식이 요법의, 규정식의":"dietary",
"관련된":"related",
"전염시키다":"transmit",
"주기적으로":"periodically",
"반응":"reaction",
"단순한":"simple",
"(보험의)보상 범위; (신문 등의)보도, 취재범위":"coverage",
"노출":"exposure",
"제약의, 약학의":"pharmaceutical",
"보험료":"premium",
"완화시키다":"relieve",
"결합, 연합":"combination",
"알고 있는, 자각하고 있는":"conscious",
"박탈, 상실":"deprivation",
"건강; (사회,기관의,)번영,안녕":"health",
"유발하다 ":"induce",
"보험":"insurance",
"영양":"nutrition",
"예방":"prevention",
"~에 감염되기 쉬운, 영향 받기 쉬운":"susceptible",
"이력서":"resume",
"지원자, 신청자":"applicant",
"필요조건, 요건":"requirement",
"(필요,요구 등을)만족시키다":"meet",
"자격있는, 적격의":"qualified",
"후보자, 지원자":"candidate",
"확신, 자신, 신임":"confidence",
"매우, 대단히":"highly",
"전문적인, 직업의, 전문가":"professional",
"면접, 면접을 보다":"interview",
"고용하다":"hire",
"교육, 훈련":"training",
"추천서, 참고":"reference",
"일자리, 직책, 두다":"position",
"성취, 달성":"achievement",
"인상 깊게 생각하는, 감명을 받은":"impressed",
"훌륭한":"excellent",
"자격이 있는, 적격의":"eligible",
"알아보다, 확인하다":"identify",
"관련시키다":"associate",
"조건":"condition",
"고용":"employment",
"~이 없다, 부족":"lack",
"관리의":"managerial",
"성실한":"diligent",
"익숙한, 친숙한":"familiar",
"숙달, 능숙":"proficiency",
"장래의, 미래의":"prospective",
"관심을 끌다, 매력적이다":"appeal",
"~을 전공하다, 전문적으로 다루다":"specialize",
"걱정하는, 염려하는":"apprehensive",
"고문, 컨설턴트":"consultant",
"자격을 주다":"entitle",
"학위":"degree",
"임금대장, 금료명부":"payroll",
"(신입사원등을)모집하다":"recruit",
"증명서, 증명":"certification",
"직업":"occupation",
"임금, 급료":"wage",
"복장, 옷차림새":"attire",
"규범, 관례;암호":"code",
"우려, 걱정, 문제, 일, ~을 걱정스럽게 하다; 영향을 미치다, 관련되다.":"concern",
"규정; 보험, 증권":"policy",
"준수하다, 따르다":"comply",
"규정":"regulation",
"예외":"exception",
"지키다, 고수하다":"adhere",
"엄격하게, 심하게":"severely",
"자제하다, 삼가다":"refrain",
"허락, 허가":"permission",
"이용권한, 접근;통로, ~에 접근하다, 도달하다":"access",
"철저하게, 완전히, 대단히":"thoroughly",
"(의견, 계획을)수정하다, 변경하다":"revise",
"접근법, 처리방법":"approach",
"승인, 인가":"approval",
"종류, 유형, 양식":"form",
"즉시, 곧":"immediately",
"점검, 검사":"inspection",
"준비, 마련, 주선":"arrangement",
"절차":"procedure",
"부정적인, 비관적인":"negative",
"명령하다, 지시하다, 권한, 지시, 명령":"mandate",
"(법률등의)효력, 효과, 영향, 결과로서 ~을 가져오다":"effect",
"심하게, 과감하게, 철저하게":"drastically",
"~에 따라":"according to",
"(무엇을)가능하게 하다":"enable",
"기준, 표준":"standard",
"지속적인, 끊임없이 계속하는":"constant",
"법령, 결의서; 행위, 행동, 결정하다, 판결을 내리다, 행동하다":"act",
"보상금, 보상":"compensation",
"금지, 금지하다":"ban",
"의무, 책임":"obligation",
"~을 인가하다, 권한을 부여하다.":"authorize",
"금지하다":"prohibit",
"(제도, 법률등을)폐지하다":"abolish",
"(법률을)시행하다, 집행하다":"enforce",
"습관, 버릇":"habit",
"법률, 법규":"lagislation",
"한정하다, 제한하다":"restrict",
"익숙한":"accustomed",
"주식회사, 법인":"corporatiion",
"요구가 많은, 힘든":"demanding",
"동료":"colleague",
"부서":"division",
"요청, 요청하다":"request",
"효율적으로":"efficiently",
"~을 경영하다; 가까스로 하다":"manage",
"제출하다":"submit",
"곧바로":"directly",
"~에게 상기시키다, 일깨우다":"remind",
"지시하다, 가르치다":"instruct",
"마감일, 마감 시간":"deadline",
"견본, 샘플, 표본시식하다, (견본으로 질을)시험하다":"sample",
"~에게 통지하다, 알리다":"notify",
"행하다, 실행하다":"perform",
"감독하다, 감시하다, 실행하다":"monitor",
"~할 만하다, ~할 가치가 있다":"deserve",
"일, 임무, 과제":"assignment",
"전체의":"entire",
"발표하다, 공개하다, 출시, 발매":"release",
"연장, 연기; (전화의)내선":"extension",
"컴퓨터 통신망으로, 컴퓨터로":"electronically",
"출석, 출근":"attendance",
"절대적으로, 완전히":"absolutely",
"(권한등을)위임하다. 대표":"delegate",
"주의 깊게, 조심스럽게":"attentively",
"감독":"supervision",
"워크숍, 연수":"workshop",
"끌다, 끌어당기다":"draw",
"수정, 개정":"revision",
"마지못해, 꺼려하여":"reluctantly",
"~에게 숙지시키다, 잘 알게 하다":"acquaint",
"(용건을)전달하다":"convey",
"검사하다, 조사하다, 확인하다":"check",
"본부":"headquarters",
"(서류를)정리하다, 철하다;(서류, 신청, 고소 등을)정식으로 제기하다, 제출하다":"file",
"감독하다 ":"oversee",
"관여하는, 관계된, 연루된":"involved",
"집중하다, 집중시키다":"concentrate",
"(행동 등이)느슨한, 규율에 못 미치는":"lax",
"미루다, 꾸물거리다":"procrastinate",
"결합된, 합동의":"combined",
"성취하다":"accomplish",
"자발적으로":"voluntarily",
"(일을)떠맡다":"undertake",
"(증거는 없으나)사실이라고 생각하다;(책임,역할을)맡다":"assume",
"가끔, 때때로":"occasionally",
"직원, 고용인":"employee",
"돕다, 조력하다":"assist",
"만족하는, 만족스러워하는":"satisfied",
"방식, 태도":"manner",
"책임이 있는, 책임져야 할":"responsible",
"(업무 등을)수행하다":"conduct",
"적응하다":"adjust",
"(집합적)직원, 인원; 인사과":"personnel",
"동의하다":"agree",
"감독하다, 지도하다":"supervise",
"동료, 협력자":"coworker",
"~에게 길을 안내하다, 가르쳐 주다":"direct",
"기밀의, 내밀한":"confidential",
"배정하다, 할당하다":"assign",
"선도적인, 일류의, 가장 중요한, 선두적인":"leading",
"격식을 갖춘":"formal",
"해임하다, 제거하다":"remove",
"모으다":"collect",
"조정하다":"coordinate",
"거의~하지않다":"hardly",
"추상적인, 막연한":"abstract",
"주소록":"directory",
"책임이 있는":"accountable",
"능숙하게, 솜씨있게":"skillfully",
"독점적인, 배타적인":"exclusive",
"의지, 의향":"intention",
"바꾸다, 변모시키다":"transform",
"정중한, 존중하는":"respectful",
"사본":"duplicate",
"반대":"contrary",
"충격적인, 불안감을 주는, 방해하는":"disturbing",
"관여하다, 종사하다":"engage",
"촉진하다, 육성하다":"foster",
"중립성, 중립":"neutrality",
"널리":"widely",
"(기계가)정교한, 복잡한; 세련된":"sophisticated",
"시기적절한, 때를 맞춘":"timely",
"현실적으로":"realistically",
"즉시; 정각에":"promptly",
"출입할 수 있는; 이용할 수 있는":"accessible",
"실시하다, 실행하다":"implement",
"의견, 반응":"feedback",
"우수한; (부채 등이)미지불된":"outstanding",
"~에게 알리다":"inform",
"교체, 후임자":"replacement",
"공고, 발표":"announcement",
"(조직, 기구의)부서":"department",
"영구적으로, 불변으로":"permanently",
"(조건을)만족시키다, (약속, 의무등을)지키다, 이행하다":"fulfill",
"개요, 설명하다, 약술하다":"outline",
"설명하다":"explain",
"포함하다":"contain",
"(자료 등을)편집하다; 모으다":"compile",
"차후의, 그 다음의":"subsequent",
"개요, 개관":"overview",
"공급자, 제공자":"provider",
"문제, 일":"matter",
"전문지식, 전문기술":"expertise",
"증명하다; (모형, 실험등으로)설명하다":"demonstrate",
"나머지":"remainder",
"필수적인, 극히 중요한, 본질적인":"essential",
"분배하다, 나누다":"divide",
"주요한, 중대한":"major",
"(명령, 법규에의)준수":"compliance",
"명확하게 하다":"clarify",
"(문제 등에)직면하다; 향하다, 마주보다":"face",
"~을 따라가다; 주시하다; (분명히)이해하다":"follow",
"관점, 국면":"aspect",
"보기에 ~한 듯한, 외관상으로는":"apparently",
"알고 있는, 인식하고 있는":"aware",
"(기간 등을)연장한, 장기간에 걸친":"extended",
"뜻하지 않게, 우연히":"accidentally",
"바람직한, 합당한":"advisable",
"염려하는, 걱정하는; 관련된":"concerned",
"이야기 하다":"speak",
"소장품, 수집물; 징수, 수금":"collection",
"전시회":"exhibition",
"유명인사, 명사":"celebrity",
"(라디오, TV가)생방송인":"live",
"(연주, 연설 등을)즉흥적으로 하다, 즉석에서 만들다.":"improvise",
"인기있는":"popular",
"기증, 기부":"donation",
"동창생들, 졸업생들":"alumni",
"제시하다, 현재의, 참석한":"present",
"입장":"admission",
};