export const SCRIPTHARD=[
    {
        "text":`컴퓨터 과학에서 병렬 컴퓨팅의 성능을 측정하는 법칙으로, 프로그램의 병렬화 가능한 부분과 직렬 실행 부분을 분석하여 성능 향상의 한계를 설명하는 법칙은 무엇인가요?`,
        1:"1. 암달의 법칙(Amdahl's Law)",
        2:"2. 무어의 법칙(Moore's Law)",
        3:"3. 파레토 법칙(Pareto Principle)",
        "correct":1,
        "WrongText":"정답은 암달의 법칙(Amdahl's Law)이야",
    },
    {
        "text":`컴퓨터 시스템에서 가상 메모리를 사용하는 동안 페이지 부재가 발생할 때, 운영 체제가 페이지 교체를 결정하는 데 사용하는 알고리즘으로, 가장 오랫동안 사용되지 않은 페이지를 교체하는 방법은 무엇인가요?`,
        1:"1. LRU(Least Recently Used)",
        2:"2. FIFO(First-In, First-Out)",
        3:"3. LFU(Least Frequently Used)",
        "correct":1,
        "WrongText":"정답은 LRU(Least Recently Used)이야",
    },
    {
        "text":`분산 시스템에서 서로 다른 노드 간의 데이터 일관성을 유지하기 위해 사용하는 프로토콜로, 네트워크 파티션, 일관성, 가용성 간의 트레이드오프를 다루는 이론은 무엇인가요?`,
        1:"1. CAP 정리(CAP Theorem)",
        2:"2. ACID 속성(ACID Properties)",
        3:"3. PACELC 정리(PACELC Theorem)",
        "correct":1,
        "WrongText":"정답은 CAP 정리(CAP Theorem)이야",
    },
    {
        "text":`데이터베이스 시스템에서 트랜잭션이 일관성을 유지하기 위해 모든 작업이 완료되거나 전혀 수행되지 않도록 보장하는 성질로, 이 성질을 위반할 경우 데이터베이스가 불일치 상태에 빠질 수 있는 것은 무엇인가요?`,
        1:"1. 원자성(Atomicity)",
        2:"2. 고립성(Isolation)",
        3:"3. 지속성(Durability)",
        "correct":1,
        "WrongText":"정답은 원자성(Atomicity)이야",
    },
    {
        "text":`운영 체제에서 교착 상태(Deadlock) 해결을 위해 자원의 할당을 추적하고, 자원의 회수를 통해 교착 상태를 피하는 알고리즘으로, 자원의 선점을 허용하지 않는 접근 방식은 무엇인가요?`,
        1:"1. 은행가 알고리즘(Banker's Algorithm)",
        2:"2. 무기한 봉쇄(Starvation)",
        3:"3. 라운드 로빈(Round Robin)",
        "correct":1,
        "WrongText":"정답은 은행가 알고리즘(Banker's Algorithm)이야",
    },
    {
        "text":`알고리즘의 효율성을 분석할 때 사용하는 개념으로, 최악의 경우를 가정하여 알고리즘의 성능을 평가하는 방법은 무엇인가요?`,
        1:"1. 빅오 표기법(Big-O Notation)",
        2:"2. 세타 표기법(Theta Notation)",
        3:"3. 오메가 표기법(Omega Notation)",
        "correct":1,
        "WrongText":"정답은 빅오 표기법(Big-O Notation)이야",
    },
    {
        "text":`컴퓨터 아키텍처에서 명령어와 데이터가 동일한 메모리 공간을 공유하며, 명령어 실행 중에 데이터가 변경될 수 있는 구조로, 파이프라인 병목 현상을 해결하는 데 어려움이 있는 이 구조는 무엇인가요?`,
        1:"1. 폰 노이만 구조(Von Neumann Architecture)",
        2:"2. 하버드 구조(Harvard Architecture)",
        3:"3. 슈퍼스칼라 구조(Superscalar Architecture)",
        "correct":1,
        "WrongText":"정답은 폰 노이만 구조(Von Neumann Architecture)이야",
    },
    {
        "text":`비교 기반의 정렬 알고리즘에서 최악의 경우에도 안정적인 성능을 보장하는 알고리즘으로, 데이터를 일정한 크기의 블록으로 나누어 정렬한 후 병합하는 방식은 무엇인가요?`,
        1:"1. 병합 정렬(Merge Sort)",
        2:"2. 퀵 정렬(Quick Sort)",
        3:"3. 힙 정렬(Heap Sort)",
        "correct":1,
        "WrongText":"정답은 병합 정렬(Merge Sort)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 패킷 교환 방식과 관련된 개념으로, 각 패킷이 독립적으로 라우팅되며, 목적지에 도달할 때까지 다른 경로를 통해 전달될 수 있는 프로토콜은 무엇인가요?`,
        1:"1. IP(Internet Protocol)",
        2:"2. MPLS(Multi-Protocol Label Switching)",
        3:"3. ATM(Asynchronous Transfer Mode)",
        "correct":1,
        "WrongText":"정답은 IP(Internet Protocol)이야",
    },
    {
        "text":`컴파일러에서 소스 코드를 기계어로 변환하는 과정 중 하나로, 변수와 함수의 주소를 결정하고, 이를 메모리 주소에 매핑하는 단계는 무엇인가요?`,
        1:"1. 링크(Linking)",
        2:"2. 로더(Loading)",
        3:"3. 바인딩(Binding)",
        "correct":1,
        "WrongText":"정답은 링크(Linking)이야",
    },
    {
        "text":`알고리즘의 최적화를 위해 사용되는 기법으로, 동일한 하위 문제를 여러 번 계산하는 대신, 결과를 저장하여 재사용하는 방식은 무엇인가요?`,
        1:"1. 메모이제이션(Memoization)",
        2:"2. 동적 계획법(Dynamic Programming)",
        3:"3. 탐욕 알고리즘(Greedy Algorithm)",
        "correct":1,
        "WrongText":"정답은 메모이제이션(Memoization)이야",
    },{
        "text":`운영 체제에서 프로세스의 상태를 관리하고, 시스템의 효율성을 높이기 위해 사용하는 기법으로, CPU와 I/O 작업의 비율을 조정하는 스케줄링 알고리즘은 무엇인가요?`,
        1:"1. 멀티레벨 큐 스케줄링(Multi-level Queue Scheduling)",
        2:"2. 라운드 로빈 스케줄링(Round Robin Scheduling)",
        3:"3. 멀티레벨 피드백 큐 스케줄링(Multi-level Feedback Queue Scheduling)",
        "correct":3,
        "WrongText":"정답은 멀티레벨 피드백 큐 스케줄링(Multi-level Feedback Queue Scheduling)이야",
    },
    {
        "text":`데이터베이스에서 트랜잭션이 일관성을 유지하면서 동시에 실행될 수 있도록 관리하는 기법으로, 서로 다른 트랜잭션 간의 상호작용을 최소화하여 데이터 무결성을 보장하는 것은 무엇인가요?`,
        1:"1. 직렬화(Serialization)",
        2:"2. 2단계 잠금 기법(Two-Phase Locking)",
        3:"3. 갱신 분리 기법(Shadow Paging)",
        "correct":2,
        "WrongText":"정답은 2단계 잠금 기법(Two-Phase Locking)이야",
    },
    {
        "text":`분산 시스템에서 노드 간의 합의(consensus)를 이끌어내기 위한 알고리즘으로, 네트워크 파티션, 메시지 지연, 프로세스 실패 상황에서도 안정적인 합의를 보장하는 알고리즘은 무엇인가요?`,
        1:"1. Paxos",
        2:"2. Raft",
        3:"3. Zookeeper's ZAB",
        "correct":1,
        "WrongText":"정답은 Paxos야",
    },
    {
        "text":`컴퓨터 그래픽스에서 물체의 표면을 사실적으로 표현하기 위해, 입사광과 반사광을 계산하여 각 픽셀의 색을 결정하는 렌더링 기법은 무엇인가요?`,
        1:"1. 레이 트레이싱(Ray Tracing)",
        2:"2. 라디오시티(Radiosity)",
        3:"3. 포톤 매핑(Photon Mapping)",
        "correct":1,
        "WrongText":"정답은 레이 트레이싱(Ray Tracing)이야",
    },
    {
        "text":`컴퓨터 시스템에서 메모리 계층 구조를 최적화하기 위해 사용하는 기법으로, 캐시 메모리의 데이터를 최신 상태로 유지하고, 프로세서의 접근 속도를 향상시키는 방법은 무엇인가요?`,
        1:"1. 캐시 일관성(Cache Coherence)",
        2:"2. 캐시 예측(Cache Prefetching)",
        3:"3. 캐시 에비션(Cache Eviction)",
        "correct":1,
        "WrongText":"정답은 캐시 일관성(Cache Coherence)이야",
    },
    {
        "text":`비교 기반 정렬 알고리즘 중 최적의 시간 복잡도를 가지며, 퀵소트와 병합 정렬의 장점을 결합한 알고리즘으로, 삽입 정렬을 사용하여 소규모 데이터셋을 처리하는 방식은 무엇인가요?`,
        1:"1. 팀소트(Timsort)",
        2:"2. 힙소트(Heapsort)",
        3:"3. 셸소트(Shellsort)",
        "correct":1,
        "WrongText":"정답은 팀소트(Timsort)이야",
    },
    {
        "text":`소프트웨어 아키텍처에서 대규모 시스템의 확장성을 보장하기 위해 사용되는 패턴으로, 마이크로서비스 간의 통신을 관리하고, 장애를 격리하는 기법은 무엇인가요?`,
        1:"1. 서킷 브레이커(Circuit Breaker)",
        2:"2. API 게이트웨이(API Gateway)",
        3:"3. 서비스 메쉬(Service Mesh)",
        "correct":3,
        "WrongText":"정답은 서비스 메쉬(Service Mesh)이야",
    },
    {
        "text":`데이터베이스에서 복잡한 쿼리를 최적화하기 위해, 쿼리의 실행 계획을 수립하고, 가장 효율적인 경로를 선택하는 역할을 하는 것은 무엇인가요?`,
        1:"1. 쿼리 옵티마이저(Query Optimizer)",
        2:"2. 인덱스 스캐너(Index Scanner)",
        3:"3. 쿼리 파서(Query Parser)",
        "correct":1,
        "WrongText":"정답은 쿼리 옵티마이저(Query Optimizer)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 DDoS 공격을 방어하기 위해, 정상적인 트래픽과 악성 트래픽을 구별하고, 네트워크 자원의 오용을 방지하는 기술은 무엇인가요?`,
        1:"1. 레이트 리미팅(Rate Limiting)",
        2:"2. IP 스푸핑(IP Spoofing)",
        3:"3. 서킷 브레이킹(Circuit Breaking)",
        "correct":1,
        "WrongText":"정답은 레이트 리미팅(Rate Limiting)이야",
    },
    {
        "text":`소프트웨어 공학에서 객체 간의 강한 결합을 피하고, 객체 간의 상호작용을 간접적으로 처리하여 코드의 유연성과 재사용성을 높이는 디자인 패턴은 무엇인가요?`,
        1:"1. 의존성 주입(Dependency Injection)",
        2:"2. 싱글톤(Singleton)",
        3:"3. 퍼사드(Facade)",
        "correct":1,
        "WrongText":"정답은 의존성 주입(Dependency Injection)이야",
    },
    {
        "text":`운영 체제에서 메모리 관리 기법 중 하나로, 가상 메모리 공간을 실제 물리 메모리에 할당하여 프로그램 실행을 관리하며, 페이지 테이블을 사용하는 이 기법은 무엇인가요?`,
        1:"1. 페이징(Paging)",
        2:"2. 세그멘테이션(Segmentation)",
        3:"3. 스와핑(Swapping)",
        "correct":1,
        "WrongText":"정답은 페이징(Paging)이야",
    },{
        "text":`컴퓨터 아키텍처에서 동일한 연산을 여러 데이터에 동시에 적용하여 성능을 향상시키는 병렬 컴퓨팅 기술로, 벡터 프로세서나 그래픽 처리 장치(GPU)에서 주로 사용되는 것은 무엇인가요?`,
        1:"1. SIMD(Single Instruction, Multiple Data)",
        2:"2. MIMD(Multiple Instruction, Multiple Data)",
        3:"3. SISD(Single Instruction, Single Data)",
        "correct":1,
        "WrongText":"정답은 SIMD(Single Instruction, Multiple Data)이야",
    },
    {
        "text":`컴퓨터 시스템에서 분산 트랜잭션을 관리하기 위한 프로토콜로, 트랜잭션의 모든 참여자 간에 합의를 통해 커밋하거나 롤백하는 것을 보장하는 이 프로토콜은 무엇인가요?`,
        1:"1. 2단계 커밋 프로토콜(Two-Phase Commit Protocol)",
        2:"2. 3단계 커밋 프로토콜(Three-Phase Commit Protocol)",
        3:"3. 분산 락 관리(Distributed Lock Manager)",
        "correct":1,
        "WrongText":"정답은 2단계 커밋 프로토콜(Two-Phase Commit Protocol)이야",
    },
    {
        "text":`암호학에서 동일한 키를 사용하여 데이터를 암호화하고 복호화하는 알고리즘으로, 속도가 빠르고 간단하지만, 키 분배 문제로 인해 보안이 취약할 수 있는 이 암호화 방식은 무엇인가요?`,
        1:"1. 대칭키 암호화(Symmetric Key Encryption)",
        2:"2. 비대칭키 암호화(Asymmetric Key Encryption)",
        3:"3. 해시 함수(Hash Function)",
        "correct":1,
        "WrongText":"정답은 대칭키 암호화(Symmetric Key Encryption)이야",
    },
    {
        "text":`분산 시스템에서 시간 동기화를 위해 사용하는 알고리즘으로, 각 노드의 로컬 시간을 중앙 서버와 동기화하고, 전체 시스템의 시간 일관성을 유지하는 이 프로토콜은 무엇인가요?`,
        1:"1. NTP(Network Time Protocol)",
        2:"2. PTP(Precision Time Protocol)",
        3:"3. Lamport's Logical Clock",
        "correct":1,
        "WrongText":"정답은 NTP(Network Time Protocol)이야",
    },
    {
        "text":`데이터베이스에서 인덱스 구조를 사용하여 검색 성능을 향상시키는 방법으로, 자주 조회되는 데이터에 대해 더 빠른 접근을 제공하며, B-트리의 변형으로 알려진 이 구조는 무엇인가요?`,
        1:"1. B+ 트리",
        2:"2. 해시 인덱스(Hash Index)",
        3:"3. B* 트리",
        "correct":1,
        "WrongText":"정답은 B+ 트리야",
    },
    {
        "text":`프로그래밍 언어 이론에서 함수가 다른 함수를 인자로 받거나 함수를 반환하는 방식으로, 함수를 일급 객체로 취급하는 개념은 무엇인가요?`,
        1:"1. 고차 함수(Higher-Order Function)",
        2:"2. 순수 함수(Pure Function)",
        3:"3. 클로저(Closure)",
        "correct":1,
        "WrongText":"정답은 고차 함수(Higher-Order Function)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 데이터의 무결성과 출처를 확인하기 위해 사용되는 알고리즘으로, 메시지에 대한 디지털 서명을 생성하고 검증하는 데 사용되는 알고리즘은 무엇인가요?`,
        1:"1. RSA",
        2:"2. DSA(Digital Signature Algorithm)",
        3:"3. MD5(Message Digest Algorithm 5)",
        "correct":2,
        "WrongText":"정답은 DSA(Digital Signature Algorithm)이야",
    },
    {
        "text":`운영 체제에서 프로세스 간의 통신을 위해 사용하는 메커니즘으로, 프로세스들이 서로 다른 주소 공간에 있을 때 메시지를 주고받는 방식은 무엇인가요?`,
        1:"1. 메시지 패싱(Message Passing)",
        2:"2. 공유 메모리(Shared Memory)",
        3:"3. 파이프(Pipes)",
        "correct":1,
        "WrongText":"정답은 메시지 패싱(Message Passing)이야",
    },
    {
        "text":`비선형 데이터 구조 중에서 우선순위가 높은 요소가 먼저 처리되도록 하는 자료구조로, 일반적으로 힙(Heap)을 사용하여 구현되는 이 구조는 무엇인가요?`,
        1:"1. 우선순위 큐(Priority Queue)",
        2:"2. 이진 검색 트리(Binary Search Tree)",
        3:"3. AVL 트리(AVL Tree)",
        "correct":1,
        "WrongText":"정답은 우선순위 큐(Priority Queue)이야",
    },
    {
        "text":`소프트웨어 공학에서 특정 객체의 생성 과정을 캡슐화하고, 동일한 생성 과정을 통해 서로 다른 객체를 생성할 수 있도록 하는 디자인 패턴은 무엇인가요?`,
        1:"1. 팩토리 메서드 패턴(Factory Method Pattern)",
        2:"2. 추상 팩토리 패턴(Abstract Factory Pattern)",
        3:"3. 빌더 패턴(Builder Pattern)",
        "correct":1,
        "WrongText":"정답은 팩토리 메서드 패턴(Factory Method Pattern)이야",
    },
    {
        "text":`컴퓨터 시스템에서 I/O 연산의 성능을 개선하기 위해, 데이터를 일정량 모아 한 번에 처리하는 방법으로, 디스크와 같은 저장 장치의 효율성을 높이는 이 기술은 무엇인가요?`,
        1:"1. 배치 처리(Batch Processing)",
        2:"2. 버퍼링(Buffering)",
        3:"3. 캐싱(Caching)",
        "correct":2,
        "WrongText":"정답은 버퍼링(Buffering)이야",
    },{
        "text":`운영 체제에서 프로세스가 메모리에서 차지하는 페이지들을 실제 물리 메모리에서 디스크로 옮겨 저장하는 과정으로, 메모리가 부족할 때 사용하는 이 기법은 무엇인가요?`,
        1:"1. 스와핑(Swapping)",
        2:"2. 페이징(Paging)",
        3:"3. 세그멘테이션(Segmentation)",
        "correct":1,
        "WrongText":"정답은 스와핑(Swapping)이야",
    },
    {
        "text":`컴퓨터 보안에서 네트워크 트래픽을 감시하고 분석하여 비정상적인 활동을 탐지하는 시스템으로, 잠재적인 침입을 실시간으로 탐지하는 이 시스템은 무엇인가요?`,
        1:"1. IDS(Intrusion Detection System)",
        2:"2. IPS(Intrusion Prevention System)",
        3:"3. 방화벽(Firewall)",
        "correct":1,
        "WrongText":"정답은 IDS(Intrusion Detection System)이야",
    },
    {
        "text":`데이터베이스에서 고가용성과 데이터 일관성을 보장하기 위해 여러 데이터베이스 인스턴스 간에 데이터베이스 트랜잭션을 복제하는 기술로, 한 노드의 실패에도 다른 노드에서 서비스를 지속할 수 있는 이 기술은 무엇인가요?`,
        1:"1. 마스터-슬레이브 복제(Master-Slave Replication)",
        2:"2. 멀티마스터 복제(Multi-Master Replication)",
        3:"3. 셰어드-나싱 아키텍처(Shared-Nothing Architecture)",
        "correct":2,
        "WrongText":"정답은 멀티마스터 복제(Multi-Master Replication)이야",
    },
    {
        "text":`프로그래밍 언어에서 변수의 유효 범위와 생명 주기를 정의하는 개념으로, 특정 블록 안에서만 접근 가능한 변수의 범위를 결정하는 것은 무엇인가요?`,
        1:"1. 스코프(Scope)",
        2:"2. 클로저(Closure)",
        3:"3. 네임스페이스(Namespace)",
        "correct":1,
        "WrongText":"정답은 스코프(Scope)이야",
    },
    {
        "text":`운영 체제에서 다중 프로세스 간의 데이터 동기화를 위해 사용하는 기술로, 동일한 자원을 동시에 접근하는 상황을 피하기 위해 사용되는 것은 무엇인가요?`,
        1:"1. 뮤텍스(Mutex)",
        2:"2. 세마포어(Semaphore)",
        3:"3. 모니터(Monitor)",
        "correct":2,
        "WrongText":"정답은 세마포어(Semaphore)이야",
    },
    {
        "text":`소프트웨어 설계에서 복잡한 시스템을 더 작고 관리 가능한 부분으로 나누어 개발하는 방법으로, 각 모듈이 독립적으로 개발되고 나중에 통합되는 설계 방식은 무엇인가요?`,
        1:"1. 모듈화(Modularization)",
        2:"2. 객체지향(Object-Oriented)",
        3:"3. 계층화(Layering)",
        "correct":1,
        "WrongText":"정답은 모듈화(Modularization)이야",
    },
    {
        "text":`컴퓨터 그래픽스에서 3D 모델의 표면을 표현하는 데 사용되는 방법으로, 물체의 표면을 그리는 데 필요한 데이터를 점(point) 단위로 계산하는 것은 무엇인가요?`,
        1:"1. 버텍스 셰이딩(Vertex Shading)",
        2:"2. 픽셀 셰이딩(Pixel Shading)",
        3:"3. 텍스처 매핑(Texture Mapping)",
        "correct":2,
        "WrongText":"정답은 픽셀 셰이딩(Pixel Shading)이야",
    },
    {
        "text":`프로그래밍 언어에서 타입 시스템이 코드의 안전성을 보장하기 위해 사용되는 방식으로, 변수가 가질 수 있는 값의 종류를 제한하여 오류를 예방하는 이 시스템은 무엇인가요?`,
        1:"1. 정적 타입 시스템(Static Type System)",
        2:"2. 동적 타입 시스템(Dynamic Type System)",
        3:"3. 약한 타입 시스템(Weak Type System)",
        "correct":1,
        "WrongText":"정답은 정적 타입 시스템(Static Type System)이야",
    },
    {
        "text":`소프트웨어 공학에서 시스템의 요구 사항을 분석하고 설계하는 단계로, 사용자의 요구를 명확히 이해하고 이를 시스템의 기능으로 변환하는 과정은 무엇인가요?`,
        1:"1. 요구 사항 분석(Requirements Analysis)",
        2:"2. 시스템 설계(System Design)",
        3:"3. 구현(Implementation)",
        "correct":1,
        "WrongText":"정답은 요구 사항 분석(Requirements Analysis)이야",
    },
    {
        "text":`컴퓨터 아키텍처에서 메모리 액세스 성능을 높이기 위해 여러 개의 캐시 메모리를 계층적으로 배치하여 관리하는 전략으로, 각 계층이 서로 다른 속도와 크기를 가지는 이 구조는 무엇인가요?`,
        1:"1. 캐시 계층 구조(Cache Hierarchy)",
        2:"2. 메모리 계층 구조(Memory Hierarchy)",
        3:"3. 다중 캐싱(Multi-Level Caching)",
        "correct":1,
        "WrongText":"정답은 캐시 계층 구조(Cache Hierarchy)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 네트워크 트래픽을 제어하고, 네트워크의 대역폭을 효율적으로 사용하는 방법으로, 트래픽 혼잡을 방지하기 위해 데이터 전송 속도를 조절하는 이 메커니즘은 무엇인가요?`,
        1:"1. 혼잡 제어(Congestion Control)",
        2:"2. 흐름 제어(Flow Control)",
        3:"3. QoS(Quality of Service)",
        "correct":1,
        "WrongText":"정답은 혼잡 제어(Congestion Control)이야",
    },
    {
        "text":`분산 시스템에서 장애 발생 시에도 시스템의 지속성을 보장하기 위해 사용하는 기술로, 장애를 감지하고 자동으로 시스템을 복구하는 이 방법은 무엇인가요?`,
        1:"1. 셀프 힐링(Self-Healing)",
        2:"2. 핫 스탠바이(Hot Standby)",
        3:"3. 콜드 스탠바이(Cold Standby)",
        "correct":1,
        "WrongText":"정답은 셀프 힐링(Self-Healing)이야",
    },{
        "text":`컴퓨터 시스템에서 프로그램이 직접 하드웨어를 조작하는 것을 방지하고, 안정성과 보안을 강화하기 위해 운영 체제가 사용하는 방법으로, 메모리 주소를 논리 주소와 물리 주소로 나누어 관리하는 이 기술은 무엇인가요?`,
        1:"1. 가상 메모리(Virtual Memory)",
        2:"2. 메모리 보호(Memory Protection)",
        3:"3. 주소 공간 레이아웃 랜덤화(Address Space Layout Randomization)",
        "correct":2,
        "WrongText":"정답은 메모리 보호(Memory Protection)이야",
    },
    {
        "text":`인공지능에서 특정 문제 해결을 위해 사용하는 휴리스틱 탐색 알고리즘 중 하나로, 노드의 비용과 예상되는 최종 목적지까지의 비용을 모두 고려하여 가장 적합한 경로를 찾는 것은 무엇인가요?`,
        1:"1. A* 알고리즘(A* Algorithm)",
        2:"2. 다익스트라 알고리즘(Dijkstra's Algorithm)",
        3:"3. BFS(너비 우선 탐색, Breadth-First Search)",
        "correct":1,
        "WrongText":"정답은 A* 알고리즘(A* Algorithm)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 통신 성능을 극대화하기 위해 사용되는 기법으로, 여러 네트워크 경로를 병렬로 사용하여 데이터를 전송함으로써 대역폭을 늘리는 이 기술은 무엇인가요?`,
        1:"1. 링크 어그리게이션(Link Aggregation)",
        2:"2. 라운드 로빈(Round Robin)",
        3:"3. 라우팅(Routing)",
        "correct":1,
        "WrongText":"정답은 링크 어그리게이션(Link Aggregation)이야",
    },
    {
        "text":`데이터베이스 관리 시스템에서 대규모 데이터셋을 효율적으로 처리하기 위해 사용하는 기술로, 데이터를 여러 조각으로 나누어 분산 시스템에서 병렬로 처리할 수 있도록 하는 이 방법은 무엇인가요?`,
        1:"1. 샤딩(Sharding)",
        2:"2. 파티셔닝(Partitioning)",
        3:"3. 인덱싱(Indexing)",
        "correct":1,
        "WrongText":"정답은 샤딩(Sharding)이야",
    },
    {
        "text":`소프트웨어 개발에서 반복적이고 점진적인 방식으로 프로젝트를 진행하는 방법론으로, 스크럼이나 칸반과 같은 프레임워크가 포함된 이 방법론은 무엇인가요?`,
        1:"1. 애자일(Agile)",
        2:"2. 폭포수(Waterfall)",
        3:"3. 스파이럴(Spiral)",
        "correct":1,
        "WrongText":"정답은 애자일(Agile)이야",
    },
    {
        "text":`컴퓨터 그래픽스에서 물체의 3차원 모델을 평면에 투영하여 2차원 이미지를 생성하는 과정에서, 물체의 깊이 정보를 고려해 가까운 물체가 먼 물체를 가리는 효과를 부여하는 기법은 무엇인가요?`,
        1:"1. Z-버퍼링(Z-Buffering)",
        2:"2. 레이 트레이싱(Ray Tracing)",
        3:"3. 래스터화(Rasterization)",
        "correct":1,
        "WrongText":"정답은 Z-버퍼링(Z-Buffering)이야",
    },
    {
        "text":`운영 체제에서 CPU 스케줄링 알고리즘 중 하나로, 각 프로세스가 동일한 크기의 시간 조각을 할당받아 실행되는 방식으로, 선점형 스케줄링의 일종인 이 방법은 무엇인가요?`,
        1:"1. 라운드 로빈(Round Robin)",
        2:"2. 우선순위 스케줄링(Priority Scheduling)",
        3:"3. 멀티레벨 큐 스케줄링(Multilevel Queue Scheduling)",
        "correct":1,
        "WrongText":"정답은 라운드 로빈(Round Robin)이야",
    },
    {
        "text":`소프트웨어 공학에서 버전 관리 시스템을 사용하여 코드를 관리할 때, 여러 개발자가 동시에 작업할 수 있도록 하고, 충돌이 발생할 경우 이를 해결할 수 있도록 하는 작업 방식은 무엇인가요?`,
        1:"1. 브랜칭(Branching)",
        2:"2. 머지(Merging)",
        3:"3. 체리 피킹(Cherry Picking)",
        "correct":1,
        "WrongText":"정답은 브랜칭(Branching)이야",
    },
    {
        "text":`컴퓨터 보안에서 권한이 없는 사용자가 시스템 자원에 접근하는 것을 방지하기 위해 사용되는 기술로, 사용자가 시스템에 로그인할 때 신원을 확인하는 과정은 무엇인가요?`,
        1:"1. 인증(Authentication)",
        2:"2. 인가(Authorization)",
        3:"3. 감사(Auditing)",
        "correct":1,
        "WrongText":"정답은 인증(Authentication)이야",
    },
    {
        "text":`운영 체제에서 프로세스 간의 협력을 가능하게 하는 메커니즘으로, 메시지를 전달하고 이벤트를 동기화하는 데 사용되는 이 방법은 무엇인가요?`,
        1:"1. 인터프로세스 커뮤니케이션(Inter-Process Communication)",
        2:"2. 시그널링(Signaling)",
        3:"3. 커널 모드(Kernel Mode)",
        "correct":1,
        "WrongText":"정답은 인터프로세스 커뮤니케이션(Inter-Process Communication)이야",
    },
    {
        "text":`알고리즘 설계에서 재귀적으로 문제를 해결하는 기법으로, 큰 문제를 더 작은 부분 문제로 나누고, 그 결과를 결합하여 전체 문제를 해결하는 방식은 무엇인가요?`,
        1:"1. 분할 정복(Divide and Conquer)",
        2:"2. 동적 계획법(Dynamic Programming)",
        3:"3. 그리디 알고리즘(Greedy Algorithm)",
        "correct":1,
        "WrongText":"정답은 분할 정복(Divide and Conquer)이야",
    },
    {
        "text":`네트워크 보안에서 전송 계층에서 통신을 암호화하여 데이터를 보호하는 프로토콜로, 웹 브라우저와 서버 간의 안전한 통신을 보장하는 이 프로토콜은 무엇인가요?`,
        1:"1. TLS(Transport Layer Security)",
        2:"2. SSL(Secure Sockets Layer)",
        3:"3. IPSec(Internet Protocol Security)",
        "correct":1,
        "WrongText":"정답은 TLS(Transport Layer Security)이야",
    },{
        "text":`컴퓨터 아키텍처에서 파이프라이닝(Pipelining)은 프로세서의 명령어 처리 성능을 높이기 위해 사용되는 기술로, 여러 명령어를 동시에 겹쳐서 처리하는 방식입니다. 이때 발생할 수 있는 파이프라인 내의 데이터 의존성을 해결하기 위한 기법은 무엇인가요?`,
        1:"1. 데이터 포워딩(Data Forwarding)",
        2:"2. 브랜치 프레딕션(Branch Prediction)",
        3:"3. 명령어 재정렬(Instruction Reordering)",
        "correct":1,
        "WrongText":"정답은 데이터 포워딩(Data Forwarding)이야",
    },
    {
        "text":`운영 체제에서 교착 상태(Deadlock)는 두 개 이상의 프로세스가 서로가 필요로 하는 자원을 점유한 채 무한히 기다리며 진행되지 못하는 상태를 말합니다. 교착 상태를 예방하기 위해 네 가지 필요 조건 중 하나를 제거하는 방법은 무엇인가요?`,
        1:"1. 자원 할당 그래프(Resource Allocation Graph)",
        2:"2. 은행원 알고리즘(Banker's Algorithm)",
        3:"3. 기아 상태(Starvation)",
        "correct":2,
        "WrongText":"정답은 은행원 알고리즘(Banker's Algorithm)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 패킷이 전송될 때, 송신 측에서 보낸 데이터가 수신 측에서 정상적으로 수신되었는지 확인하는 메커니즘을 제공하는 프로토콜은 무엇인가요?`,
        1:"1. TCP(Transmission Control Protocol)",
        2:"2. UDP(User Datagram Protocol)",
        3:"3. ICMP(Internet Control Message Protocol)",
        "correct":1,
        "WrongText":"정답은 TCP(Transmission Control Protocol)이야",
    },
    {
        "text":`알고리즘에서 NP-완전 문제(NP-Complete Problem)는 다항식 시간 내에 해결할 수 없는 것으로 알려져 있으며, NP-완전 문제에 대해 다항식 시간 내에 해를 구하는 알고리즘이 존재할 가능성에 대한 추측은 무엇인가요?`,
        1:"1. P=NP 추측",
        2:"2. NP-난해 문제(NP-Hard Problem)",
        3:"3. NP-추정 문제(NP-Approximation Problem)",
        "correct":1,
        "WrongText":"정답은 P=NP 추측이야",
    },
    {
        "text":`컴퓨터 보안에서 프로그램이나 시스템이 허용되지 않은 사용자나 시스템으로부터의 액세스를 방지하는 메커니즘을 제공하는데, 이 중 사용자의 행위나 요청이 정당한지를 판단하는 과정은 무엇인가요?`,
        1:"1. 인가(Authorization)",
        2:"2. 인증(Authentication)",
        3:"3. 감사(Auditing)",
        "correct":1,
        "WrongText":"정답은 인가(Authorization)이야",
    },
    {
        "text":`데이터베이스에서 트랜잭션은 일련의 데이터베이스 연산을 하나의 작업 단위로 처리합니다. 트랜잭션의 ACID 속성 중에서 트랜잭션이 성공적으로 완료된 후에만 데이터베이스가 일관된 상태로 유지됨을 보장하는 것은 무엇인가요?`,
        1:"1. 일관성(Consistency)",
        2:"2. 격리성(Isolation)",
        3:"3. 원자성(Atomicity)",
        "correct":1,
        "WrongText":"정답은 일관성(Consistency)이야",
    },
    {
        "text":`프로그래밍 언어에서 함수형 프로그래밍(Function Programming)은 상태와 가변 데이터를 피하고, 함수의 조합을 통해 문제를 해결합니다. 이 패러다임에서 중요한 개념으로, 함수가 동일한 입력에 대해 항상 동일한 출력을 반환하는 성질은 무엇인가요?`,
        1:"1. 순수 함수(Pure Function)",
        2:"2. 고계 함수(Higher-Order Function)",
        3:"3. 불변성(Immutability)",
        "correct":1,
        "WrongText":"정답은 순수 함수(Pure Function)이야",
    },
    {
        "text":`운영 체제에서 페이지 교체 알고리즘은 메모리에서 페이지가 꽉 찼을 때 어떤 페이지를 교체할지 결정하는 방법입니다. 가장 오랫동안 사용되지 않은 페이지를 교체하는 이 알고리즘은 무엇인가요?`,
        1:"1. LRU(Least Recently Used)",
        2:"2. FIFO(First In, First Out)",
        3:"3. LFU(Least Frequently Used)",
        "correct":1,
        "WrongText":"정답은 LRU(Least Recently Used)이야",
    },
    {
        "text":`소프트웨어 공학에서 설계 패턴(Design Pattern)은 자주 발생하는 문제에 대한 일반적인 해결책을 제공합니다. 객체 지향 프로그래밍에서 객체 간의 상호작용을 정의하는 패턴으로, 객체가 메시지를 주고받는 방식을 정의하는 이 패턴은 무엇인가요?`,
        1:"1. 행위 패턴(Behavioral Pattern)",
        2:"2. 구조 패턴(Structural Pattern)",
        3:"3. 생성 패턴(Creational Pattern)",
        "correct":1,
        "WrongText":"정답은 행위 패턴(Behavioral Pattern)이야",
    },
    {
        "text":`컴퓨터 그래픽스에서 렌더링(Rendering)은 3D 모델로부터 최종 이미지를 생성하는 과정입니다. 렌더링 기술 중에서 빛의 경로를 시뮬레이션하여 현실적인 조명 효과를 생성하는 방법은 무엇인가요?`,
        1:"1. 레이 트레이싱(Ray Tracing)",
        2:"2. 래스터화(Rasterization)",
        3:"3. 그림자 매핑(Shadow Mapping)",
        "correct":1,
        "WrongText":"정답은 레이 트레이싱(Ray Tracing)이야",
    },
    {
        "text":`데이터 구조에서 트리(Tree)는 계층적 데이터를 저장하는 데 사용됩니다. 트리 구조에서 자식 노드가 두 개 이하인 트리의 특별한 형태를 무엇이라고 하나요?`,
        1:"1. 이진 트리(Binary Tree)",
        2:"2. AVL 트리(AVL Tree)",
        3:"3. 레드-블랙 트리(Red-Black Tree)",
        "correct":1,
        "WrongText":"정답은 이진 트리(Binary Tree)이야",
    },
    {
        "text":`분산 시스템에서 캡틴 이론(CAP Theorem)은 네트워크에서 데이터 일관성, 가용성, 네트워크 파티션 허용성을 동시에 충족시킬 수 없다는 이론입니다. 이 세 가지 속성 중에서 네트워크 분할이 발생할 때, 데이터 일관성과 가용성 중 하나를 선택해야 한다는 것은 무엇인가요?`,
        1:"1. 일관성(Consistency)",
        2:"2. 가용성(Availability)",
        3:"3. 파티션 허용성(Partition Tolerance)",
        "correct":3,
        "WrongText":"정답은 파티션 허용성(Partition Tolerance)이야",
    },{
        "text":`컴퓨터 네트워크에서 데이터 전송의 신뢰성을 보장하기 위해 사용하는 프로토콜로, 데이터 전송 중 패킷 손실, 중복, 순서 변경 등을 감지하고 수정하는 이 프로토콜은 무엇인가요?`,
        1:"1. TCP(Transmission Control Protocol)",
        2:"2. UDP(User Datagram Protocol)",
        3:"3. HTTP(Hypertext Transfer Protocol)",
        "correct":1,
        "WrongText":"정답은 TCP(Transmission Control Protocol)이야",
    },
    {
        "text":`소프트웨어 개발에서 복잡한 시스템을 여러 독립적인 모듈로 나누어 각 모듈이 독립적으로 개발되도록 하는 접근 방식으로, 시스템의 각 모듈이 서로 통신하고 협력하는 이 접근 방식은 무엇인가요?`,
        1:"1. 모듈화(Modularization)",
        2:"2. 계층화(Layering)",
        3:"3. 객체 지향 프로그래밍(Object-Oriented Programming)",
        "correct":1,
        "WrongText":"정답은 모듈화(Modularization)이야",
    },
    {
        "text":`데이터베이스에서 ACID 속성 중 하나로, 트랜잭션이 완료되면 데이터베이스의 상태가 일관된 상태로 유지되어야 한다는 원칙은 무엇인가요?`,
        1:"1. 일관성(Consistency)",
        2:"2. 격리성(Isolation)",
        3:"3. 원자성(Atomicity)",
        "correct":1,
        "WrongText":"정답은 일관성(Consistency)이야",
    },
    {
        "text":`알고리즘에서 특정 문제를 해결하기 위해 사용하는 기법으로, 문제를 해결하는 데 필요한 연산을 이전에 계산한 결과를 이용하여 효율적으로 해결하는 방식은 무엇인가요?`,
        1:"1. 동적 계획법(Dynamic Programming)",
        2:"2. 그리디 알고리즘(Greedy Algorithm)",
        3:"3. 분할 정복(Divide and Conquer)",
        "correct":1,
        "WrongText":"정답은 동적 계획법(Dynamic Programming)이야",
    },
    {
        "text":`운영 체제에서 프로세스 간의 자원 공유를 방지하기 위해 사용되는 메커니즘으로, 여러 프로세스가 동시에 접근할 수 있는 공유 자원을 관리하는 방법은 무엇인가요?`,
        1:"1. 세마포어(Semaphore)",
        2:"2. 뮤텍스(Mutex)",
        3:"3. 모니터(Monitor)",
        "correct":2,
        "WrongText":"정답은 뮤텍스(Mutex)이야",
    },
    {
        "text":`네트워크 보안에서 악성 소프트웨어가 사용자 시스템에 침투하여 비밀번호, 금융 정보 등을 탈취하는 공격 방식으로, 사용자가 신뢰할 수 있는 사이트를 사칭하여 사용자 정보를 훔치는 방법은 무엇인가요?`,
        1:"1. 피싱(Phishing)",
        2:"2. 스팸(Spam)",
        3:"3. 멀웨어(Malware)",
        "correct":1,
        "WrongText":"정답은 피싱(Phishing)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 패킷의 전송 경로를 동적으로 조정하여 네트워크 트래픽의 부하를 분산하는 기술로, 패킷이 전송될 때 가장 효율적인 경로를 선택하는 이 기술은 무엇인가요?`,
        1:"1. 라우팅(Routing)",
        2:"2. 스위칭(Switching)",
        3:"3. 브로드캐스팅(Broadcasting)",
        "correct":1,
        "WrongText":"정답은 라우팅(Routing)이야",
    },
    {
        "text":`소프트웨어 설계에서 객체 지향 프로그래밍의 원칙 중 하나로, 객체가 데이터를 숨기고 이를 접근하는 방법을 정의하여 객체의 내부 상태를 보호하는 이 원칙은 무엇인가요?`,
        1:"1. 캡슐화(Encapsulation)",
        2:"2. 상속(Inheritance)",
        3:"3. 다형성(Polymorphism)",
        "correct":1,
        "WrongText":"정답은 캡슐화(Encapsulation)이야",
    },
    {
        "text":`분산 시스템에서 장애 발생 시 데이터 일관성과 시스템의 가용성을 유지하기 위해 사용하는 기술로, 데이터 복제를 통해 여러 노드에 데이터를 저장하는 이 방법은 무엇인가요?`,
        1:"1. 데이터 복제(Data Replication)",
        2:"2. 데이터 샤딩(Data Sharding)",
        3:"3. 데이터 파티셔닝(Data Partitioning)",
        "correct":1,
        "WrongText":"정답은 데이터 복제(Data Replication)이야",
    },
    {
        "text":`컴퓨터 시스템에서 CPU와 메모리 간의 데이터 전송을 관리하는 하드웨어 장치로, 메모리 접근 속도를 높이고 CPU의 성능을 최적화하는 이 장치는 무엇인가요?`,
        1:"1. 캐시(Cache)",
        2:"2. 버퍼(Buffer)",
        3:"3. 레지스터(Register)",
        "correct":1,
        "WrongText":"정답은 캐시(Cache)이야",
    },
    {
        "text":`소프트웨어 개발에서 객체지향 설계 원칙 중 하나로, 서로 관련이 있는 데이터를 처리하는 메서드가 동일한 클래스 내에 포함되어야 한다는 원칙은 무엇인가요?`,
        1:"1. 응집도(Cohesion)",
        2:"2. 결합도(Coupling)",
        3:"3. 상속(Inheritance)",
        "correct":1,
        "WrongText":"정답은 응집도(Cohesion)이야",
    },
    {
        "text":`운영 체제에서 다중 프로그래밍 환경에서 프로세스가 사용하는 메모리의 효율성을 높이기 위해 메모리를 페이지 단위로 관리하고, 페이지의 위치를 동적으로 조정하는 이 기법은 무엇인가요?`,
        1:"1. 페이지 교체(Page Replacement)",
        2:"2. 가상 메모리(Virtual Memory)",
        3:"3. 메모리 분할(Memory Segmentation)",
        "correct":1,
        "WrongText":"정답은 페이지 교체(Page Replacement)이야",
    },{
        "text":`컴퓨터 시스템에서 자원의 경쟁을 방지하고 프로세스 간의 상호작용을 조율하기 위해 사용되는 동기화 기법 중 하나로, 동시에 여러 프로세스가 자원에 접근하는 것을 제어하는 이 기법은 무엇인가요?`,
        1:"1. 뮤텍스(Mutex)",
        2:"2. 세마포어(Semaphore)",
        3:"3. 모니터(Monitor)",
        "correct":2,
        "WrongText":"정답은 세마포어(Semaphore)이야",
    },
    {
        "text":`분산 시스템에서 데이터의 일관성을 유지하고, 여러 노드 간의 데이터를 동기화하기 위해 사용하는 기술로, 분산 트랜잭션의 일관성을 보장하기 위한 프로토콜은 무엇인가요?`,
        1:"1. 2PC(2-Phase Commit)",
        2:"2. 3PC(3-Phase Commit)",
        3:"3. Paxos 알고리즘(Paxos Algorithm)",
        "correct":1,
        "WrongText":"정답은 2PC(2-Phase Commit)이야",
    },
    {
        "text":`소프트웨어 개발에서 객체 간의 관계를 명확히 하고, 객체의 상호작용을 정의하는 패턴으로, 객체가 서로 메시지를 주고받아 작업을 수행하는 이 패턴은 무엇인가요?`,
        1:"1. 행동 패턴(Behavioral Pattern)",
        2:"2. 구조 패턴(Structural Pattern)",
        3:"3. 생성 패턴(Creational Pattern)",
        "correct":1,
        "WrongText":"정답은 행동 패턴(Behavioral Pattern)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 패킷이 손상되거나 변형되었는지 검사하는 기술로, 전송된 데이터의 무결성을 확인하기 위해 사용되는 이 기술은 무엇인가요?`,
        1:"1. 체크섬(Checksum)",
        2:"2. 해시(Hash)",
        3:"3. 암호화(Encryption)",
        "correct":1,
        "WrongText":"정답은 체크섬(Checksum)이야",
    },
    {
        "text":`컴퓨터 아키텍처에서 명령어 집합 구조(Instruction Set Architecture)에서 제공하는 명령어의 종류와 형식, 그리고 이 명령어들이 처리하는 데이터의 형식을 정의하는 이 개념은 무엇인가요?`,
        1:"1. ISA(Instruction Set Architecture)",
        2:"2. CPU(central Processing Unit)",
        3:"3. ALU(Arithmetic Logic Unit)",
        "correct":1,
        "WrongText":"정답은 ISA(Instruction Set Architecture)이야",
    },
    {
        "text":`데이터베이스에서 트랜잭션이 서로 독립적으로 실행되도록 보장하는 원칙으로, 트랜잭션 간의 상호 영향을 최소화하여 데이터 일관성을 유지하는 이 원칙은 무엇인가요?`,
        1:"1. 격리성(Isolation)",
        2:"2. 원자성(Atomicity)",
        3:"3. 일관성(Consistency)",
        "correct":1,
        "WrongText":"정답은 격리성(Isolation)이야",
    },
    {
        "text":`프로그램이 소스 코드에서 작성된 함수를 호출하는 방식 중, 호출된 함수가 호출자 함수의 상태를 유지하면서 실행되도록 하는 이 방식은 무엇인가요?`,
        1:"1. 스택 기반 호출(Stack-Based Call)",
        2:"2. 힙 기반 호출(Heap-Based Call)",
        3:"3. 레지스터 기반 호출(Register-Based Call)",
        "correct":1,
        "WrongText":"정답은 스택 기반 호출(Stack-Based Call)이야",
    },
    {
        "text":`네트워크에서 라우팅 프로토콜의 일종으로, 네트워크의 트래픽 부하를 분산하기 위해 경로를 동적으로 조정하는 알고리즘으로, 경로의 비용을 기반으로 최적의 경로를 선택하는 이 알고리즘은 무엇인가요?`,
        1:"1. OSPF(Open Shortest Path First)",
        2:"2. BGP(Border Gateway Protocol)",
        3:"3. RIP(Routing Information Protocol)",
        "correct":1,
        "WrongText":"정답은 OSPF(Open Shortest Path First)이야",
    },
    {
        "text":`알고리즘에서 검색과 정렬과 같은 기본적인 작업을 수행할 때 사용하는 데이터 구조로, 데이터를 계층적으로 저장하여 빠른 검색과 정렬이 가능하게 하는 이 구조는 무엇인가요?`,
        1:"1. 이진 검색 트리(Binary Search Tree)",
        2:"2. 해시 테이블(Hash Table)",
        3:"3. 배열(Array)",
        "correct":1,
        "WrongText":"정답은 이진 검색 트리(Binary Search Tree)이야",
    },
    {
        "text":`컴퓨터 보안에서 클라우드 환경에서 가상 머신(Virtual Machine)을 보호하기 위해 사용하는 기술로, 하드웨어와 소프트웨어 사이에 가상화 계층을 추가하여 보안을 강화하는 이 기술은 무엇인가요?`,
        1:"1. 하이퍼바이저(Hypervisor)",
        2:"2. 방화벽(Firewall)",
        3:"3. 침입 탐지 시스템(IDS)",
        "correct":1,
        "WrongText":"정답은 하이퍼바이저(Hypervisor)이야",
    },
    {
        "text":`운영 체제에서 프로세스의 실행 순서를 조정하는 기법으로, 프로세스가 CPU를 점유하기 위해 대기하는 시간을 최소화하고, 시스템의 응답성을 높이기 위한 이 기법은 무엇인가요?`,
        1:"1. 스케줄링(Scheduling)",
        2:"2. 컨텍스트 스위칭(Context Switching)",
        3:"3. 메모리 관리(Memory Management)",
        "correct":1,
        "WrongText":"정답은 스케줄링(Scheduling)이야",
    },{
        "text":`컴퓨터 과학에서, 데이터베이스의 정규화(Normalization)는 데이터의 중복을 줄이고, 데이터 무결성을 보장하기 위해 사용하는 프로세스입니다. 이 과정에서 사용하는 정규형 중, 모든 결정자에 대해 속성 집합이 슈퍼키(Superkey)여야 한다는 요구를 가지는 정규형은 무엇인가요?`,
        1:"1. 제 2 정규형(2NF)",
        2:"2. 제 3 정규형(3NF)",
        3:"3. 보이스-코드 정규형(BCNF)",
        "correct":3,
        "WrongText":"정답은 보이스-코드 정규형(BCNF)이야",
    },
    {
        "text":`암호화에서 공개 키 암호화(Public Key Cryptography)는 비대칭 암호화 기법을 사용하여 데이터를 암호화합니다. 이 기법에서 사용하는 두 개의 키 중, 데이터 암호화와 복호화를 위해 공개되는 키는 무엇인가요?`,
        1:"1. 공개 키(Public Key)",
        2:"2. 개인 키(Private Key)",
        3:"3. 대칭 키(Symmetric Key)",
        "correct":1,
        "WrongText":"정답은 공개 키(Public Key)이야",
    },
    {
        "text":`데이터베이스 트랜잭션의 ACID 속성 중, 트랜잭션이 완료되거나 중단될 때, 데이터베이스의 모든 변경 사항이 지속되도록 보장하는 원칙은 무엇인가요?`,
        1:"1. 지속성(Persistence)",
        2:"2. 원자성(Atomicity)",
        3:"3. 일관성(Consistency)",
        "correct":1,
        "WrongText":"정답은 지속성(Persistence)이야",
    },
    {
        "text":`컴퓨터 시스템에서 프로세스 간의 통신을 위해 사용되는 IPC(Inter-Process Communication) 메커니즘 중, 메모리의 특정 영역을 여러 프로세스가 공유하여 데이터를 교환하는 방식은 무엇인가요?`,
        1:"1. 공유 메모리(Shared Memory)",
        2:"2. 메시지 큐(Message Queue)",
        3:"3. 파이프(Pipe)",
        "correct":1,
        "WrongText":"정답은 공유 메모리(Shared Memory)이야",
    },
    {
        "text":`알고리즘 분석에서, 입력 크기가 n일 때 알고리즘의 실행 시간이 n^2에 비례하는 복잡도를 가지는 이 알고리즘의 시간 복잡도를 무엇이라고 하나요?`,
        1:"1. 이차 시간 복잡도(O(n^2))",
        2:"2. 선형 시간 복잡도(O(n))",
        3:"3. 로그 선형 시간 복잡도(O(n log n))",
        "correct":1,
        "WrongText":"정답은 이차 시간 복잡도(O(n^2))이야",
    },
    {
        "text":`운영 체제에서 프로세스 간의 자원 경쟁을 방지하기 위해, 여러 프로세스가 동시에 접근할 수 있는 자원을 조정하고 보호하는 이 기법은 무엇인가요?`,
        1:"1. 동기화(Synchronization)",
        2:"2. 스케줄링(Scheduling)",
        3:"3. 메모리 관리(Memory Management)",
        "correct":1,
        "WrongText":"정답은 동기화(Synchronization)이야",
    },
    {
        "text":`소프트웨어 설계에서 객체 지향 설계 원칙 중, 객체가 스스로 상태를 관리하고, 상태 변경을 다른 객체에 알리지 않도록 하는 이 원칙은 무엇인가요?`,
        1:"1. 정보 은닉(Information Hiding)",
        2:"2. 상속(Inheritance)",
        3:"3. 다형성(Polymorphism)",
        "correct":1,
        "WrongText":"정답은 정보 은닉(Information Hiding)이야",
    },
    {
        "text":`컴퓨터 네트워크에서 IP 주소를 사용하여 데이터를 전송할 때, 패킷이 목적지까지 도달할 수 있도록 중간 노드에서 사용하는 프로토콜로, 패킷이 손상되지 않도록 검증하는 이 프로토콜은 무엇인가요?`,
        1:"1. IP(Internet Protocol)",
        2:"2. ARP(Address Resolution Protocol)",
        3:"3. ICMP(Internet Control Message Protocol)",
        "correct":3,
        "WrongText":"정답은 ICMP(Internet Control Message Protocol)이야",
    },
    {
        "text":`클라우드 컴퓨팅에서 제공되는 서비스 모델 중, 가상화된 컴퓨팅 자원을 제공하여 사용자가 운영 체제와 애플리케이션을 직접 관리할 수 있도록 하는 서비스 모델은 무엇인가요?`,
        1:"1. IaaS(Infrastructure as a Service)",
        2:"2. PaaS(Platform as a Service)",
        3:"3. SaaS(Software as a Service)",
        "correct":1,
        "WrongText":"정답은 IaaS(Infrastructure as a Service)이야",
    },
    {
        "text":`알고리즘의 복잡도 분석에서, 알고리즘의 실행 시간이 입력 크기에 비례하는 경우, 이 알고리즘의 시간 복잡도를 무엇이라고 하나요?`,
        1:"1. 선형 시간 복잡도(O(n))",
        2:"2. 상수 시간 복잡도(O(1))",
        3:"3. 로그 시간 복잡도(O(log n))",
        "correct":1,
        "WrongText":"정답은 선형 시간 복잡도(O(n))이야",
    },
    {
        "text":`컴퓨터 보안에서 데이터의 기밀성과 무결성을 보장하기 위해, 데이터를 암호화하고 복호화하는 과정에서 사용하는 알고리즘으로, 동일한 키를 사용하여 암호화와 복호화를 수행하는 기법은 무엇인가요?`,
        1:"1. 대칭 암호화(Symmetric Encryption)",
        2:"2. 비대칭 암호화(Asymmetric Encryption)",
        3:"3. 해시 함수(Hash Function)",
        "correct":1,
        "WrongText":"정답은 대칭 암호화(Symmetric Encryption)이야",
    },{
        "text":`컴퓨터 네트워크에서 데이터 전송의 신뢰성을 보장하기 위해 사용하는 프로토콜로, 흐름 제어와 혼잡 제어 기능을 포함하여 패킷의 손실과 순서 변경을 감지하고 수정하는 이 프로토콜은 무엇인가요?`,
        1:"1. TCP(Transmission Control Protocol)",
        2:"2. UDP(User Datagram Protocol)",
        3:"3. IP(Internet Protocol)",
        "correct":1,
        "WrongText":"정답은 TCP(Transmission Control Protocol)이야",
    },
    {
        "text":`클라우드 컴퓨팅의 서비스 모델 중, 개발자가 애플리케이션을 구축하고 실행할 수 있는 플랫폼을 제공하는 이 서비스 모델은 무엇인가요?`,
        1:"1. PaaS(Platform as a Service)",
        2:"2. IaaS(Infrastructure as a Service)",
        3:"3. SaaS(Software as a Service)",
        "correct":1,
        "WrongText":"정답은 PaaS(Platform as a Service)이야",
    },
    {
        "text":`데이터베이스의 정규화 과정에서, 특정 속성이 다른 속성에 의해 결정되지 않도록 보장하는 정규형으로, 이 정규형을 만족하려면 모든 비주요 속성이 기본 키의 부분 집합에 의존하지 않아야 합니다. 이 정규형은 무엇인가요?`,
        1:"1. 제 1 정규형(1NF)",
        2:"2. 제 2 정규형(2NF)",
        3:"3. 제 3 정규형(3NF)",
        "correct":2,
        "WrongText":"정답은 제 2 정규형(2NF)이야",
    },
    {
        "text":`알고리즘에서 문제를 해결하기 위해 가장 작은 단위로 나누어 각 단위를 재귀적으로 해결한 다음, 결과를 결합하여 전체 문제를 해결하는 기법은 무엇인가요?`,
        1:"1. 분할 정복(Divide and Conquer)",
        2:"2. 동적 계획법(Dynamic Programming)",
        3:"3. 그리디 알고리즘(Greedy Algorithm)",
        "correct":1,
        "WrongText":"정답은 분할 정복(Divide and Conquer)이야",
    },
    {
        "text":`운영 체제에서 프로세스가 실행되기 위해 필요한 메모리 공간을 동적으로 할당하는 기법으로, 프로세스가 필요한 만큼 메모리를 할당받고, 불필요해지면 반환하는 이 기법은 무엇인가요?`,
        1:"1. 가상 메모리(Virtual Memory)",
        2:"2. 페이지 교체(Page Replacement)",
        3:"3. 메모리 스와핑(Memory Swapping)",
        "correct":1,
        "WrongText":"정답은 가상 메모리(Virtual Memory)이야",
    },
    {
        "text":`운영 체제에서 프로세스 간의 동기화를 관리하기 위해 사용하는 동기화 도구로, 프로세스가 자원을 점유하고 있을 때 다른 프로세스의 접근을 차단하는 이 도구는 무엇인가요?`,
        1:"1. 뮤텍스(Mutex)",
        2:"2. 세마포어(Semaphore)",
        3:"3. 모니터(Monitor)",
        "correct":1,
        "WrongText":"정답은 뮤텍스(Mutex)이야",
    },
    {
        "text":`네트워크 보안에서, 네트워크 트래픽의 패턴을 분석하여 비정상적인 행동을 탐지하고 이를 방지하기 위해 사용하는 기술로, 네트워크에서 발생할 수 있는 침입을 식별하는 이 기술은 무엇인가요?`,
        1:"1. 침입 탐지 시스템(IDS)",
        2:"2. 침입 방지 시스템(IPS)",
        3:"3. 방화벽(Firewall)",
        "correct":1,
        "WrongText":"정답은 침입 탐지 시스템(IDS)이야",
    },
    {
        "text":`알고리즘 분석에서 입력 크기 n에 대해 알고리즘의 실행 시간이 O(n^3)인 경우, 이 알고리즘의 시간 복잡도를 무엇이라고 하나요?`,
        1:"1. 삼차 시간 복잡도(O(n^3))",
        2:"2. 이차 시간 복잡도(O(n^2))",
        3:"3. 선형 시간 복잡도(O(n))",
        "correct":1,
        "WrongText":"정답은 삼차 시간 복잡도(O(n^3))이야",
    },
    {
        "text":`소프트웨어 공학에서, 프로그램의 유지보수와 확장을 용이하게 하기 위해 프로그램을 모듈화하여 독립적인 기능 단위로 나누는 이 원칙은 무엇인가요?`,
        1:"1. 모듈화(Modularization)",
        2:"2. 상속(Inheritance)",
        3:"3. 캡슐화(Encapsulation)",
        "correct":1,
        "WrongText":"정답은 모듈화(Modularization)이야",
    },
    {
        "text":`컴퓨터 시스템에서 물리적인 메모리의 일부를 논리적 메모리로 변환하여 프로세스가 더 큰 메모리 공간을 사용하는 것처럼 보이게 하는 기술로, 메모리 관리의 기법 중 하나는 무엇인가요?`,
        1:"1. 가상 메모리(Virtual Memory)",
        2:"2. 메모리 스와핑(Memory Swapping)",
        3:"3. 페이지 테이블(Page Table)",
        "correct":1,
        "WrongText":"정답은 가상 메모리(Virtual Memory)이야",
    },
    {
        "text":`컴퓨터 과학에서, 데이터베이스 시스템에서 효율적인 데이터 검색과 처리를 위해 사용하는 인덱스 구조 중 하나로, B-트리와 유사한 데이터 구조를 사용하는 이 인덱스는 무엇인가요?`,
        1:"1. B+ 트리(B+ Tree)",
        2:"2. 해시 인덱스(Hash Index)",
        3:"3. 비트맵 인덱스(Bitmap Index)",
        "correct":1,
        "WrongText":"정답은 B+ 트리(B+ Tree)이야",
    },
    {
        "text":`소프트웨어 개발에서, 코드의 복잡성을 줄이고 유지보수성을 향상시키기 위해 사용되는 디자인 패턴 중 하나로, 객체의 생성과 관련된 책임을 분리하여 객체 생성을 캡슐화하는 이 패턴은 무엇인가요?`,
        1:"1. 생성 패턴(Creational Pattern)",
        2:"2. 구조 패턴(Structural Pattern)",
        3:"3. 행동 패턴(Behavioral Pattern)",
        "correct":1,
        "WrongText":"정답은 생성 패턴(Creational Pattern)이야",
    },{
        "text":`알고리즘에서 자주 사용하는 기법 중, 문제를 해결하기 위해 특정 부분 문제를 저장해두고 재사용하여 중복 계산을 줄이는 이 기법은 무엇인가요?`,
        1:"1. 동적 계획법(Dynamic Programming)",
        2:"2. 분할 정복(Divide and Conquer)",
        3:"3. 그리디 알고리즘(Greedy Algorithm)",
        "correct":1,
        "WrongText":"정답은 동적 계획법(Dynamic Programming)이야",
    },
    {
        "text":`컴퓨터 시스템에서, 메모리에서 데이터를 읽고 쓰기 위해 사용하는 주소 지정 모드 중, 데이터의 주소를 직접 지정하는 방식은 무엇인가요?`,
        1:"1. 직접 주소 지정(Direct Addressing)",
        2:"2. 간접 주소 지정(Indirect Addressing)",
        3:"3. 인덱스 주소 지정(Index Addressing)",
        "correct":1,
        "WrongText":"정답은 직접 주소 지정(Direct Addressing)이야",
    },
    {
        "text":`컴퓨터 네트워크에서, IP 주소를 기반으로 네트워크의 범위와 호스트를 식별하는 데 사용되는 서브넷 마스크의 주요 기능은 무엇인가요?`,
        1:"1. 네트워크와 호스트의 범위를 구분하는 기능",
        2:"2. 데이터 패킷의 암호화 기능",
        3:"3. 네트워크 속도 조절 기능",
        "correct":1,
        "WrongText":"정답은 네트워크와 호스트의 범위를 구분하는 기능이야",
    },
    {
        "text":`운영 체제에서, 프로세스가 메모리 공간을 요청하고 할당된 메모리를 해제하는 과정을 관리하는 기법으로, 동적 메모리 할당 및 해제를 포함하는 이 기법은 무엇인가요?`,
        1:"1. 메모리 관리(Memory Management)",
        2:"2. 파일 시스템 관리(File System Management)",
        3:"3. 스케줄링(Scheduling)",
        "correct":1,
        "WrongText":"정답은 메모리 관리(Memory Management)이야",
    },
    {
        "text":`소프트웨어 설계에서 객체의 행위와 상태를 캡슐화하여 코드의 재사용성과 유지보수성을 높이기 위한 원칙으로, 객체의 내부 상태를 외부에서 직접 접근하지 못하도록 하는 이 원칙은 무엇인가요?`,
        1:"1. 캡슐화(Encapsulation)",
        2:"2. 상속(Inheritance)",
        3:"3. 다형성(Polymorphism)",
        "correct":1,
        "WrongText":"정답은 캡슐화(Encapsulation)이야",
    },
    {
        "text":`컴퓨터 시스템에서, 데이터의 보안성을 강화하기 위해 사용되는 접근 제어 리스트(ACL)와 유사한 보안 정책으로, 리소스에 대한 권한을 사용자나 그룹에 따라 설정하는 이 정책은 무엇인가요?`,
        1:"1. 역할 기반 접근 제어(Role-Based Access Control)",
        2:"2. 임의 접근 제어(Mandatory Access Control)",
        3:"3. 권한 기반 접근 제어(Discretionary Access Control)",
        "correct":1,
        "WrongText":"정답은 역할 기반 접근 제어(Role-Based Access Control)이야",
    },
    {
        "text":`네트워크에서, 특정 노드가 네트워크의 상태를 지속적으로 모니터링하고, 패킷을 송신 및 수신하는 작업을 수행하는 역할을 맡고 있는 이 장치는 무엇인가요?`,
        1:"1. 라우터(Router)",
        2:"2. 스위치(Switch)",
        3:"3. 허브(Hub)",
        "correct":1,
        "WrongText":"정답은 라우터(Router)이야",
    },
    {
        "text":`데이터베이스에서, 트랜잭션의 일관성을 보장하기 위해 사용하는 원칙으로, 트랜잭션이 완료되면 데이터베이스의 상태가 일관되게 유지되도록 보장하는 이 원칙은 무엇인가요?`,
        1:"1. 일관성(Consistency)",
        2:"2. 원자성(Atomicity)",
        3:"3. 격리성(Isolation)",
        "correct":1,
        "WrongText":"정답은 일관성(Consistency)이야",
    },
    {
        "text":`운영 체제에서, 프로세스가 실행 중인 상태에서 다른 프로세스의 메모리 영역을 접근하는 것을 방지하기 위해 사용하는 메모리 보호 기법으로, 프로세스 간의 메모리 공간을 격리하는 이 기법은 무엇인가요?`,
        1:"1. 메모리 보호(Memory Protection)",
        2:"2. 가상 메모리(Virtual Memory)",
        3:"3. 페이지 교체(Page Replacement)",
        "correct":1,
        "WrongText":"정답은 메모리 보호(Memory Protection)이야",
    },
    {
        "text":`클라우드 컴퓨팅의 서비스 모델 중, 사용자에게 완전한 소프트웨어 애플리케이션을 제공하고, 소프트웨어의 유지보수와 업데이트를 클라우드 서비스 제공자가 담당하는 이 모델은 무엇인가요?`,
        1:"1. SaaS(Software as a Service)",
        2:"2. PaaS(Platform as a Service)",
        3:"3. IaaS(Infrastructure as a Service)",
        "correct":1,
        "WrongText":"정답은 SaaS(Software as a Service)이야",
    },
    {
        "text":`알고리즘의 시간 복잡도 분석에서, 입력 크기 n에 대해 알고리즘의 실행 시간이 O(log n)인 경우, 이 알고리즘의 시간 복잡도를 무엇이라고 하나요?`,
        1:"1. 로그 시간 복잡도(O(log n))",
        2:"2. 선형 시간 복잡도(O(n))",
        3:"3. 이차 시간 복잡도(O(n^2))",
        "correct":1,
        "WrongText":"정답은 로그 시간 복잡도(O(log n))이야",
    },
    {
        "text":`운영 체제에서, 프로세스가 CPU를 점유할 때, 다른 프로세스가 CPU를 점유할 수 있도록 현재 프로세스의 상태를 저장하고, 이후 복원하는 이 과정을 무엇이라고 하나요?`,
        1:"1. 컨텍스트 스위칭(Context Switching)",
        2:"2. 프로세스 스케줄링(Process Scheduling)",
        3:"3. 메모리 관리(Memory Management)",
        "correct":1,
        "WrongText":"정답은 컨텍스트 스위칭(Context Switching)이야",
    },{
        "text":`컴퓨터 과학에서, 데이터베이스의 트랜잭션 처리에서 일관성을 유지하기 위해 ACID 속성 중 하나로, 모든 트랜잭션이 완료되거나 중단될 때, 시스템이 중단된 경우에도 데이터베이스의 상태가 복구 가능한 이 속성은 무엇인가요?`,
        1:"1. 지속성(Persistence)",
        2:"2. 원자성(Atomicity)",
        3:"3. 격리성(Isolation)",
        "correct":1,
        "WrongText":"정답은 지속성(Persistence)이야",
    },
    {
        "text":`컴퓨터 네트워크에서, 두 네트워크 간의 연결을 설정하고 데이터를 전송하는 데 사용되는 프로토콜 중, 전송의 신뢰성을 보장하기 위해 3-way 핸드쉐이크(Three-way Handshake) 과정을 사용하는 프로토콜은 무엇인가요?`,
        1:"1. TCP(Transmission Control Protocol)",
        2:"2. UDP(User Datagram Protocol)",
        3:"3. IP(Internet Protocol)",
        "correct":1,
        "WrongText":"정답은 TCP(Transmission Control Protocol)이야",
    },
    {
        "text":`컴퓨터 시스템에서, 사용자에게 애플리케이션을 제공하고, 애플리케이션의 성능, 안정성, 보안을 보장하기 위해 사용하는 이론적인 모델로, 애플리케이션과 하드웨어 사이의 중간 계층 역할을 하는 이 모델은 무엇인가요?`,
        1:"1. 가상화(Virtualization)",
        2:"2. 클라우드 컴퓨팅(Cloud Computing)",
        3:"3. 운영 체제(Operating System)",
        "correct":1,
        "WrongText":"정답은 가상화(Virtualization)이야",
    },
    {
        "text":`운영 체제에서, 프로세스의 자원 요구를 효율적으로 관리하고, 시스템의 응답성을 유지하기 위해 사용되는 기법 중, 프로세스의 우선 순위를 조정하여 CPU 자원을 배분하는 이 기법은 무엇인가요?`,
        1:"1. 스케줄링(Scheduling)",
        2:"2. 메모리 관리(Memory Management)",
        3:"3. 페이지 교체(Page Replacement)",
        "correct":1,
        "WrongText":"정답은 스케줄링(Scheduling)이야",
    },
    {
        "text":`컴퓨터 보안에서, 악성 소프트웨어가 시스템에 침투하여 데이터의 무결성을 손상시키거나 시스템 자원을 악용하는 것을 방지하기 위해 사용하는 보안 기술로, 시스템의 다양한 계층에서 보안 정책을 적용하는 이 기술은 무엇인가요?`,
        1:"1. 다계층 보안(Multi-layer Security)",
        2:"2. 침입 탐지 시스템(IDS)",
        3:"3. 방화벽(Firewall)",
        "correct":1,
        "WrongText":"정답은 다계층 보안(Multi-layer Security)이야",
    },
    {
        "text":`알고리즘에서, 입력 데이터의 정렬을 수행할 때, 평균 시간 복잡도가 O(n log n)인 정렬 알고리즘으로, 병합 정렬(Merge Sort)과 유사한 기법을 사용하는 이 알고리즘은 무엇인가요?`,
        1:"1. 퀵 정렬(Quick Sort)",
        2:"2. 힙 정렬(Heap Sort)",
        3:"3. 삽입 정렬(Insertion Sort)",
        "correct":1,
        "WrongText":"정답은 퀵 정렬(Quick Sort)이야",
    },
    {
        "text":`컴퓨터 시스템에서, 동시성 문제를 해결하기 위해 여러 프로세스가 동일한 자원에 접근할 때, 데이터의 일관성을 유지하도록 보장하는 기술로, 자원을 공유하는 프로세스 간의 상호 배제(mutual exclusion)를 구현하는 이 기술은 무엇인가요?`,
        1:"1. 세마포어(Semaphore)",
        2:"2. 뮤텍스(Mutex)",
        3:"3. 모니터(Monitor)",
        "correct":2,
        "WrongText":"정답은 뮤텍스(Mutex)이야",
    },
    {
        "text":`네트워크의 패킷 전송에서, 데이터의 전송 오류를 검출하고 수정하기 위해 사용하는 기법으로, 오류 검출 및 수정 코드와 관련된 기법으로, 패킷의 무결성을 보장하는 이 기법은 무엇인가요?`,
        1:"1. CRC(Cyclic Redundancy Check)",
        2:"2. 해시(Hash)",
        3:"3. 체크섬(Checksum)",
        "correct":1,
        "WrongText":"정답은 CRC(Cyclic Redundancy Check)이야",
    },
    {
        "text":`소프트웨어 공학에서, 대규모 소프트웨어 시스템의 구조를 설계할 때, 시스템의 주요 구성 요소를 정의하고, 각 구성 요소 간의 관계를 명확히 하는 이 접근 방식은 무엇인가요?`,
        1:"1. 아키텍처 설계(Architecture Design)",
        2:"2. 구현(Implementation)",
        3:"3. 테스트(Testing)",
        "correct":1,
        "WrongText":"정답은 아키텍처 설계(Architecture Design)이야",
    },
    {
        "text":`운영 체제에서, 프로세스의 상태를 변경하거나 프로세스 간의 자원 접근을 제어하기 위해 사용하는 기법으로, 자원 요청 및 할당을 관리하여 데드락을 방지하는 이 기법은 무엇인가요?`,
        1:"1. 자원 할당 그래프(Resource Allocation Graph)",
        2:"2. 프로세스 스케줄링(Process Scheduling)",
        3:"3. 페이지 교체(Page Replacement)",
        "correct":1,
        "WrongText":"정답은 자원 할당 그래프(Resource Allocation Graph)이야",
    },
    {
        "text":`알고리즘 분석에서, 입력 크기 n에 대해 알고리즘의 실행 시간이 O(2^n)인 경우, 이 알고리즘의 시간 복잡도를 무엇이라고 하나요?`,
        1:"1. 지수 시간 복잡도(O(2^n))",
        2:"2. 로그 시간 복잡도(O(log n))",
        3:"3. 선형 시간 복잡도(O(n))",
        "correct":1,
        "WrongText":"정답은 지수 시간 복잡도(O(2^n))이야",
    },{
        "text":`객체 지향 프로그래밍에서, 객체가 자신이 속한 클래스의 특성을 상속받아 새로운 클래스를 생성할 때 사용하는 이 개념은 무엇인가요?`,
        1:"1. 상속(Inheritance)",
        2:"2. 다형성(Polymorphism)",
        3:"3. 캡슐화(Encapsulation)",
        "correct":1,
        "WrongText":"정답은 상속(Inheritance)이야",
    },
    {
        "text":`데이터베이스 설계에서, 정규화를 통해 테이블의 중복을 줄이고 무결성을 보장하기 위한 과정 중, 모든 비주요 속성이 기본 키에 전적으로 의존하도록 하는 이 정규형은 무엇인가요?`,
        1:"1. 제 2 정규형(2NF)",
        2:"2. 제 3 정규형(3NF)",
        3:"3. BCNF(Boyce-Codd Normal Form)",
        "correct":2,
        "WrongText":"정답은 제 3 정규형(3NF)이야",
    },
    {
        "text":`운영 체제에서, 프로세스가 메모리의 특정 위치에 있는 데이터를 읽고 쓸 때 사용하는 주소 지정 모드로, 메모리 위치를 상대적으로 지정하는 이 모드는 무엇인가요?`,
        1:"1. 상대 주소 지정(Relative Addressing)",
        2:"2. 절대 주소 지정(Absolute Addressing)",
        3:"3. 간접 주소 지정(Indirect Addressing)",
        "correct":1,
        "WrongText":"정답은 상대 주소 지정(Relative Addressing)이야",
    },
    {
        "text":`알고리즘에서, 문제를 해결하기 위해 문제를 점진적으로 해결하는 방식으로, 전체 문제를 작은 부분 문제로 나누어 해결한 후 결합하는 이 기법은 무엇인가요?`,
        1:"1. 분할 정복(Divide and Conquer)",
        2:"2. 동적 계획법(Dynamic Programming)",
        3:"3. 그리디 알고리즘(Greedy Algorithm)",
        "correct":1,
        "WrongText":"정답은 분할 정복(Divide and Conquer)이야",
    },
    {
        "text":`클라우드 컴퓨팅의 서비스 모델 중, 사용자에게 컴퓨팅 자원(서버, 저장소 등)을 제공하고, 이 자원을 직접 관리할 수 있는 이 모델은 무엇인가요?`,
        1:"1. IaaS(Infrastructure as a Service)",
        2:"2. PaaS(Platform as a Service)",
        3:"3. SaaS(Software as a Service)",
        "correct":1,
        "WrongText":"정답은 IaaS(Infrastructure as a Service)이야",
    },
    {
        "text":`네트워크 보안에서, 내부 네트워크와 외부 네트워크 간의 접속을 통제하고, 외부의 공격으로부터 내부 네트워크를 보호하기 위해 사용하는 이 장치는 무엇인가요?`,
        1:"1. 방화벽(Firewall)",
        2:"2. 침입 탐지 시스템(IDS)",
        3:"3. 침입 방지 시스템(IPS)",
        "correct":1,
        "WrongText":"정답은 방화벽(Firewall)이야",
    },
    {
        "text":`소프트웨어 개발에서, 코드의 복잡성을 줄이고, 유지보수성과 확장성을 높이기 위해 클래스를 객체로 나누어 독립적인 책임을 가지도록 하는 이 원칙은 무엇인가요?`,
        1:"1. 단일 책임 원칙(Single Responsibility Principle)",
        2:"2. 개방-폐쇄 원칙(Open/Closed Principle)",
        3:"3. 리스코프 치환 원칙(Liskov Substitution Principle)",
        "correct":1,
        "WrongText":"정답은 단일 책임 원칙(Single Responsibility Principle)이야",
    },
    {
        "text":`컴퓨터 시스템에서, 프로그램의 명령어를 기계어로 변환하여 CPU가 이해할 수 있도록 하는 이 과정을 무엇이라고 하나요?`,
        1:"1. 컴파일(Compilation)",
        2:"2. 해석(Interpretation)",
        3:"3. 링킹(Linking)",
        "correct":1,
        "WrongText":"정답은 컴파일(Compilation)이야",
    },
    {
        "text":`운영 체제에서, 메모리의 여러 프로세스가 동시에 실행될 때, 프로세스 간의 메모리 보호와 관리 기능을 제공하는 이 기술은 무엇인가요?`,
        1:"1. 가상 메모리(Virtual Memory)",
        2:"2. 메모리 스와핑(Memory Swapping)",
        3:"3. 페이지 교체(Page Replacement)",
        "correct":1,
        "WrongText":"정답은 가상 메모리(Virtual Memory)이야",
    },
    {
        "text":`알고리즘 분석에서, 입력 크기 n에 대해 알고리즘의 실행 시간이 O(n^2)인 경우, 이 알고리즘의 시간 복잡도를 무엇이라고 하나요?`,
        1:"1. 이차 시간 복잡도(O(n^2))",
        2:"2. 선형 시간 복잡도(O(n))",
        3:"3. 로그 시간 복잡도(O(log n))",
        "correct":1,
        "WrongText":"정답은 이차 시간 복잡도(O(n^2))이야",
    },
    {
        "text":`데이터베이스에서, ACID 속성 중, 데이터의 무결성을 유지하기 위해 트랜잭션이 완전히 수행되거나 수행되지 않도록 보장하는 이 속성은 무엇인가요?`,
        1:"1. 원자성(Atomicity)",
        2:"2. 일관성(Consistency)",
        3:"3. 격리성(Isolation)",
        "correct":1,
        "WrongText":"정답은 원자성(Atomicity)이야",
    },
    {
        "text":`네트워크에서, 패킷의 흐름을 제어하고, 네트워크 혼잡을 방지하기 위해 사용하는 프로토콜로, 흐름 제어와 혼잡 제어를 지원하는 이 프로토콜은 무엇인가요?`,
        1:"1. TCP(Transmission Control Protocol)",
        2:"2. UDP(User Datagram Protocol)",
        3:"3. ARP(Address Resolution Protocol)",
        "correct":1,
        "WrongText":"정답은 TCP(Transmission Control Protocol)이야",
    }
]